package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import tpoffline.utils.UtilsAC;

/**
 * Entity mapped to table "ARTICULO_HISTORICO_VENTA".
 */
public class ArticuloHistoricoVenta implements java.io.Serializable {

    private Long idarticulo;
    private Long idproducto;
    private Long idcoleccion;
    private String codigobarra;
    private String referencia;
    private String descripcion;
    private Double precioventaeq;
    private Double preciocostoeq;
    private Double preciocostoreal;
    private Double preciocostorealeq;
    private double totalDet;
    private double preciofactura;
    private String color;
    private String talle;
    private long cantidadDet;
    private long porcentajeDescuentoDet;
    private double precioDet;
    private double impuestoDet;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ArticuloHistoricoVenta() {
    }

    public ArticuloHistoricoVenta(Long idarticulo) {
        this.idarticulo = idarticulo;
    }

    public ArticuloHistoricoVenta(Long idarticulo, Long idproducto, Long idcoleccion, String codigobarra, String referencia, String descripcion, Double precioventaeq, Double preciocostoeq, Double preciocostoreal, Double preciocostorealeq, double totalDet, double preciofactura, String color, String talle, long cantidadDet, long porcentajeDescuentoDet, double precioDet, double impuestoDet) {
        this.idarticulo = idarticulo;
        this.idproducto = idproducto;
        this.idcoleccion = idcoleccion;
        this.codigobarra = codigobarra;
        this.referencia = referencia;
        this.descripcion = descripcion;
        this.precioventaeq = precioventaeq;
        this.preciocostoeq = preciocostoeq;
        this.preciocostoreal = preciocostoreal;
        this.preciocostorealeq = preciocostorealeq;
        this.totalDet = totalDet;
        this.preciofactura = preciofactura;
        this.color = color;
        this.talle = talle;
        this.cantidadDet = cantidadDet;
        this.porcentajeDescuentoDet = porcentajeDescuentoDet;
        this.precioDet = precioDet;
        this.impuestoDet = impuestoDet;
    }

    public Long getIdarticulo() {
        return idarticulo;
    }

    public void setIdarticulo(Long idarticulo) {
        this.idarticulo = idarticulo;
    }

    public Long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(Long idproducto) {
        this.idproducto = idproducto;
    }

    public Long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(Long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    public String getCodigobarra() {
        return codigobarra;
    }

    public void setCodigobarra(String codigobarra) {
        this.codigobarra = codigobarra;
    }

    public String getReferencia() {
        return referencia;
    }

    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Double getPrecioventaeq() {
        return precioventaeq;
    }

    public void setPrecioventaeq(Double precioventaeq) {
        this.precioventaeq = precioventaeq;
    }

    public Double getPreciocostoeq() {
        return preciocostoeq;
    }

    public void setPreciocostoeq(Double preciocostoeq) {
        this.preciocostoeq = preciocostoeq;
    }

    public Double getPreciocostoreal() {
        return preciocostoreal;
    }

    public void setPreciocostoreal(Double preciocostoreal) {
        this.preciocostoreal = preciocostoreal;
    }

    public Double getPreciocostorealeq() {
        return preciocostorealeq;
    }

    public void setPreciocostorealeq(Double preciocostorealeq) {
        this.preciocostorealeq = preciocostorealeq;
    }

    public double getTotalDet() {
        return totalDet;
    }

    public void setTotalDet(double totalDet) {
        this.totalDet = totalDet;
    }

    public double getPreciofactura() {
        return preciofactura;
    }

    public void setPreciofactura(double preciofactura) {
        this.preciofactura = preciofactura;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getTalle() {
        return talle;
    }

    public void setTalle(String talle) {
        this.talle = talle;
    }

    public long getCantidadDet() {
        return cantidadDet;
    }

    public void setCantidadDet(long cantidadDet) {
        this.cantidadDet = cantidadDet;
    }

    public long getPorcentajeDescuentoDet() {
        return porcentajeDescuentoDet;
    }

    public void setPorcentajeDescuentoDet(long porcentajeDescuentoDet) {
        this.porcentajeDescuentoDet = porcentajeDescuentoDet;
    }

    public double getPrecioDet() {
        return precioDet;
    }

    public void setPrecioDet(double precioDet) {
        this.precioDet = precioDet;
    }

    public double getImpuestoDet() {
        return impuestoDet;
    }

    public void setImpuestoDet(double impuestoDet) {
        this.impuestoDet = impuestoDet;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public boolean equals(Object oa) {
        boolean esIgual = false;
        if (oa == null) {
            esIgual = false;
        } else
        if (oa instanceof ArticuloHistoricoVenta) {
            ArticuloHistoricoVenta otroa = (ArticuloHistoricoVenta) oa;
            if (otroa.getIdarticulo().equals(this.getIdarticulo())) {
                esIgual = true;
            } else {
                esIgual = false;
            }
        }

        return esIgual;

    }

    @Override
    public int hashCode() {
        return UtilsAC.ti(getIdarticulo());
    }
    // KEEP METHODS END

}
