package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ARTICULO_UBICACION".
 */
public class ArticuloUbicacion implements java.io.Serializable {

    private Long idarticulosucursalubicacion;
    private Long idarticulo;
    private Long codsucursal;
    private Long iddeposito;
    private Long idestanteria;
    private Long idrack;
    private Long idbandeja;
    private Long cantidad;
    private Long cantidadvirtual;
    private Long idbox;
    private Long idproducto;
    private Long idcoleccion;
    private Long codgrade;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ArticuloUbicacion() {
    }

    public ArticuloUbicacion(Long idarticulosucursalubicacion) {
        this.idarticulosucursalubicacion = idarticulosucursalubicacion;
    }

    public ArticuloUbicacion(Long idarticulosucursalubicacion, Long idarticulo, Long codsucursal, Long iddeposito, Long idestanteria, Long idrack, Long idbandeja, Long cantidad, Long cantidadvirtual, Long idbox, Long idproducto, Long idcoleccion, Long codgrade) {
        this.idarticulosucursalubicacion = idarticulosucursalubicacion;
        this.idarticulo = idarticulo;
        this.codsucursal = codsucursal;
        this.iddeposito = iddeposito;
        this.idestanteria = idestanteria;
        this.idrack = idrack;
        this.idbandeja = idbandeja;
        this.cantidad = cantidad;
        this.cantidadvirtual = cantidadvirtual;
        this.idbox = idbox;
        this.idproducto = idproducto;
        this.idcoleccion = idcoleccion;
        this.codgrade = codgrade;
    }

    public Long getIdarticulosucursalubicacion() {
        return idarticulosucursalubicacion;
    }

    public void setIdarticulosucursalubicacion(Long idarticulosucursalubicacion) {
        this.idarticulosucursalubicacion = idarticulosucursalubicacion;
    }

    public Long getIdarticulo() {
        return idarticulo;
    }

    public void setIdarticulo(Long idarticulo) {
        this.idarticulo = idarticulo;
    }

    public Long getCodsucursal() {
        return codsucursal;
    }

    public void setCodsucursal(Long codsucursal) {
        this.codsucursal = codsucursal;
    }

    public Long getIddeposito() {
        return iddeposito;
    }

    public void setIddeposito(Long iddeposito) {
        this.iddeposito = iddeposito;
    }

    public Long getIdestanteria() {
        return idestanteria;
    }

    public void setIdestanteria(Long idestanteria) {
        this.idestanteria = idestanteria;
    }

    public Long getIdrack() {
        return idrack;
    }

    public void setIdrack(Long idrack) {
        this.idrack = idrack;
    }

    public Long getIdbandeja() {
        return idbandeja;
    }

    public void setIdbandeja(Long idbandeja) {
        this.idbandeja = idbandeja;
    }

    public Long getCantidad() {
        return cantidad;
    }

    public void setCantidad(Long cantidad) {
        this.cantidad = cantidad;
    }

    public Long getCantidadvirtual() {
        return cantidadvirtual;
    }

    public void setCantidadvirtual(Long cantidadvirtual) {
        this.cantidadvirtual = cantidadvirtual;
    }

    public Long getIdbox() {
        return idbox;
    }

    public void setIdbox(Long idbox) {
        this.idbox = idbox;
    }

    public Long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(Long idproducto) {
        this.idproducto = idproducto;
    }

    public Long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(Long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    public Long getCodgrade() {
        return codgrade;
    }

    public void setCodgrade(Long codgrade) {
        this.codgrade = codgrade;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
