package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BARRIO".
 */
public class Barrio implements java.io.Serializable {

    private Long idbarrio;
    /** Not-null value. */
    private String descripcion;
    private Long idlocalidad;

    // KEEP FIELDS - put your custom fields here

    public static final Object NINGUNO_DESCONOCIDO = new Barrio(-1L, "Desconocido", -1L);
    // KEEP FIELDS END

    public Barrio() {
    }

    public Barrio(Long idbarrio) {
        this.idbarrio = idbarrio;
    }

    public Barrio(Long idbarrio, String descripcion, Long idlocalidad) {
        this.idbarrio = idbarrio;
        this.descripcion = descripcion;
        this.idlocalidad = idlocalidad;
    }

    public Long getIdbarrio() {
        return idbarrio;
    }

    public void setIdbarrio(Long idbarrio) {
        this.idbarrio = idbarrio;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Long getIdlocalidad() {
        return idlocalidad;
    }

    public void setIdlocalidad(Long idlocalidad) {
        this.idlocalidad = idlocalidad;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        // TODO Auto-generated method stub
        return getDescripcion().toUpperCase();
    }
    // KEEP METHODS END

}
