package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BOX".
 */
public class Box implements java.io.Serializable {

    private Long idbox;
    /** Not-null value. */
    private String descripcion;

    // KEEP FIELDS - put your custom fields here
    public static final long ID_BOX_PASILLO = 9999;
    // KEEP FIELDS END

    public Box() {
    }

    public Box(Long idbox) {
        this.idbox = idbox;
    }

    public Box(Long idbox, String descripcion) {
        this.idbox = idbox;
        this.descripcion = descripcion;
    }

    public Long getIdbox() {
        return idbox;
    }

    public void setIdbox(Long idbox) {
        this.idbox = idbox;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
