package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CLIENTE_LOG".
 */
public class ClienteLog {

    private Long idclientelog;
    private Long idtipoclientelog;
    /** Not-null value. */
    private java.util.Date fecha;
    /** Not-null value. */
    private String observacion;
    private long idusuario;
    private long idcliente;
    /** Not-null value. */
    private String usuario;
    /** Not-null value. */
    private String responsable;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ClienteLog() {
    }

    public ClienteLog(Long idclientelog) {
        this.idclientelog = idclientelog;
    }

    public ClienteLog(Long idclientelog, Long idtipoclientelog, java.util.Date fecha, String observacion, long idusuario, long idcliente, String usuario, String responsable) {
        this.idclientelog = idclientelog;
        this.idtipoclientelog = idtipoclientelog;
        this.fecha = fecha;
        this.observacion = observacion;
        this.idusuario = idusuario;
        this.idcliente = idcliente;
        this.usuario = usuario;
        this.responsable = responsable;
    }

    public Long getIdclientelog() {
        return idclientelog;
    }

    public void setIdclientelog(Long idclientelog) {
        this.idclientelog = idclientelog;
    }

    public Long getIdtipoclientelog() {
        return idtipoclientelog;
    }

    public void setIdtipoclientelog(Long idtipoclientelog) {
        this.idtipoclientelog = idtipoclientelog;
    }

    /** Not-null value. */
    public java.util.Date getFecha() {
        return fecha;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    /** Not-null value. */
    public String getObservacion() {
        return observacion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public long getIdusuario() {
        return idusuario;
    }

    public void setIdusuario(long idusuario) {
        this.idusuario = idusuario;
    }

    public long getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(long idcliente) {
        this.idcliente = idcliente;
    }

    /** Not-null value. */
    public String getUsuario() {
        return usuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /** Not-null value. */
    public String getResponsable() {
        return responsable;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
