package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CLIENTE_PIN".
 */
public class ClientePin implements java.io.Serializable {

    private Long idcliente;
    /** Not-null value. */
    private String nrodocumento;
    private long clientepin;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ClientePin() {
    }

    public ClientePin(Long idcliente) {
        this.idcliente = idcliente;
    }

    public ClientePin(Long idcliente, String nrodocumento, long clientepin) {
        this.idcliente = idcliente;
        this.nrodocumento = nrodocumento;
        this.clientepin = clientepin;
    }

    public Long getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(Long idcliente) {
        this.idcliente = idcliente;
    }

    /** Not-null value. */
    public String getNrodocumento() {
        return nrodocumento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNrodocumento(String nrodocumento) {
        this.nrodocumento = nrodocumento;
    }

    public long getClientepin() {
        return clientepin;
    }

    public void setClientepin(long clientepin) {
        this.clientepin = clientepin;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
