package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "COLECCION".
 */
public class Coleccion implements java.io.Serializable {

    private Long idcoleccion;
    /** Not-null value. */
    private String descripcion;
    private Boolean estado;
    private Boolean vigente;

    // KEEP FIELDS - put your custom fields here
    /*  usar siempre constante => -1234567890L */
    private static final long TODAS_LAS_COLECCIONES_ID =-1L;
    private static final long NINGUNA_COLECCION_ID =-2L;

    public static final Coleccion COLECCION_TODAS_LAS_COLECCIONES = new Coleccion(TODAS_LAS_COLECCIONES_ID,
            "TODAS LAS COLECCIONES", true, false);

    public static final Coleccion COLECCION_NINGUNA = new Coleccion(NINGUNA_COLECCION_ID,
            "Ninguno", true,false);
    public static final long ID_COLECCION_TILIBRA_ESPECIAL = 20;
    public static final long ID_COLECCION_QUIMICOS_ESPECIAL = 26;
    public static final long ID_COLECCION_CAJOVIL_ESPECIAL = 73;
    // KEEP FIELDS END

    public Coleccion() {
    }

    public Coleccion(Long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    public Coleccion(Long idcoleccion, String descripcion, Boolean estado, Boolean vigente) {
        this.idcoleccion = idcoleccion;
        this.descripcion = descripcion;
        this.estado = estado;
        this.vigente = vigente;
    }

    public Long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(Long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Boolean getVigente() {
        return vigente;
    }

    public void setVigente(Boolean vigente) {
        this.vigente = vigente;
    }

    // KEEP METHODS - put your custom methods here

    public boolean esColeccionSaldoVenta() {
        return getIdcoleccion().longValue() == TODAS_LAS_COLECCIONES_ID ;
    }


    @Override
    public String toString() {
        if(getIdcoleccion().longValue() == TODAS_LAS_COLECCIONES_ID ) {
            return getDescripcion();
        } else {
            return getIdcoleccion() + " " + getDescripcion();
        }


    }
    // KEEP METHODS END

}
