package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CONFIGURACION_LOCAL_TABLET".
 */
public class ConfiguracionLocalTablet implements java.io.Serializable {

    private Long idconfiguracionlocal;
    /** Not-null value. */
    private String clave;
    /** Not-null value. */
    private String valor;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ConfiguracionLocalTablet() {
    }

    public ConfiguracionLocalTablet(Long idconfiguracionlocal) {
        this.idconfiguracionlocal = idconfiguracionlocal;
    }

    public ConfiguracionLocalTablet(Long idconfiguracionlocal, String clave, String valor) {
        this.idconfiguracionlocal = idconfiguracionlocal;
        this.clave = clave;
        this.valor = valor;
    }

    public Long getIdconfiguracionlocal() {
        return idconfiguracionlocal;
    }

    public void setIdconfiguracionlocal(Long idconfiguracionlocal) {
        this.idconfiguracionlocal = idconfiguracionlocal;
    }

    /** Not-null value. */
    public String getClave() {
        return clave;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClave(String clave) {
        this.clave = clave;
    }

    /** Not-null value. */
    public String getValor() {
        return valor;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValor(String valor) {
        this.valor = valor;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
