package empresa.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import empresa.dao.*;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productoDaoConfig;
    private final DaoConfig datosGeneralesEmpresaDaoConfig;
    private final DaoConfig facturaCabDaoConfig;
    private final DaoConfig coleccionDaoConfig;
    private final DaoConfig usuarioProductoDaoConfig;
    private final DaoConfig coleccionEmbarqueDaoConfig;
    private final DaoConfig coleccionProductoDaoConfig;
    private final DaoConfig usuarioDaoConfig;
    private final DaoConfig clienteDaoConfig;
    private final DaoConfig cliente2DaoConfig;
    private final DaoConfig articuloDaoConfig;
    private final DaoConfig articuloHistoricoVentaDaoConfig;
    private final DaoConfig formaPagoDaoConfig;
    private final DaoConfig referenciaDaoConfig;
    private final DaoConfig clienteFidelidadDaoConfig;
    private final DaoConfig ventaCabDaoConfig;
    private final DaoConfig ventaDetDaoConfig;
    private final DaoConfig tipoClienteLogDaoConfig;
    private final DaoConfig clienteLogDaoConfig;
    private final DaoConfig estadoAplicacionDaoConfig;
    private final DaoConfig familiaDaoConfig;
    private final DaoConfig tipoPersonaDaoConfig;
    private final DaoConfig tipoDocumentoDaoConfig;
    private final DaoConfig tipoClienteDaoConfig;
    private final DaoConfig localidadDaoConfig;
    private final DaoConfig regionDaoConfig;
    private final DaoConfig zonaDaoConfig;
    private final DaoConfig rubroDaoConfig;
    private final DaoConfig barrioDaoConfig;
    private final DaoConfig lineaArticuloDaoConfig;
    private final DaoConfig ultimaVentaDaoConfig;
    private final DaoConfig programaVisitaDaoConfig;
    private final DaoConfig grupoLineaArticuloDaoConfig;
    private final DaoConfig estadoPedidoHechoDaoConfig;
    private final DaoConfig promedioPorColeccionDaoConfig;
    private final DaoConfig promocionDaoConfig;
    private final DaoConfig configuracionRemotaTabletDaoConfig;
    private final DaoConfig escalaDaoConfig;
    private final DaoConfig grupoMultiplicadorDaoConfig;
    private final DaoConfig productMigradoFabricaDaoConfig;
    private final DaoConfig imagenArticuloDaoConfig;
    private final DaoConfig empresaUsuarioDaoConfig;
    private final DaoConfig empresaDaoConfig;
    private final DaoConfig configuracionLocalTabletDaoConfig;
    private final DaoConfig articuloUbicacionDaoConfig;
    private final DaoConfig boxDaoConfig;
    private final DaoConfig referenciaUbicacionBoxDaoConfig;
    private final DaoConfig metavendedorclienteDaoConfig;
    private final DaoConfig clienteProductoDaoConfig;
    private final DaoConfig metaVendedorDaoConfig;
    private final DaoConfig formaPagoDetDaoConfig;
    private final DaoConfig clientePinDaoConfig;
    private final DaoConfig descuentoArticuloDaoConfig;
    private final DaoConfig localidadVentacabDaoConfig;

    private final ProductoDao productoDao;
    private final DatosGeneralesEmpresaDao datosGeneralesEmpresaDao;
    private final FacturaCabDao facturaCabDao;
    private final ColeccionDao coleccionDao;
    private final UsuarioProductoDao usuarioProductoDao;
    private final ColeccionEmbarqueDao coleccionEmbarqueDao;
    private final ColeccionProductoDao coleccionProductoDao;
    private final UsuarioDao usuarioDao;
    private final ClienteDao clienteDao;
    private final Cliente2Dao cliente2Dao;
    private final ArticuloDao articuloDao;
    private final ArticuloHistoricoVentaDao articuloHistoricoVentaDao;
    private final FormaPagoDao formaPagoDao;
    private final ReferenciaDao referenciaDao;
    private final ClienteFidelidadDao clienteFidelidadDao;
    private final VentaCabDao ventaCabDao;
    private final VentaDetDao ventaDetDao;
    private final TipoClienteLogDao tipoClienteLogDao;
    private final ClienteLogDao clienteLogDao;
    private final EstadoAplicacionDao estadoAplicacionDao;
    private final FamiliaDao familiaDao;
    private final TipoPersonaDao tipoPersonaDao;
    private final TipoDocumentoDao tipoDocumentoDao;
    private final TipoClienteDao tipoClienteDao;
    private final LocalidadDao localidadDao;
    private final RegionDao regionDao;
    private final ZonaDao zonaDao;
    private final RubroDao rubroDao;
    private final BarrioDao barrioDao;
    private final LineaArticuloDao lineaArticuloDao;
    private final UltimaVentaDao ultimaVentaDao;
    private final ProgramaVisitaDao programaVisitaDao;
    private final GrupoLineaArticuloDao grupoLineaArticuloDao;
    private final EstadoPedidoHechoDao estadoPedidoHechoDao;
    private final PromedioPorColeccionDao promedioPorColeccionDao;
    private final PromocionDao promocionDao;
    private final ConfiguracionRemotaTabletDao configuracionRemotaTabletDao;
    private final EscalaDao escalaDao;
    private final GrupoMultiplicadorDao grupoMultiplicadorDao;
    private final ProductMigradoFabricaDao productMigradoFabricaDao;
    private final ImagenArticuloDao imagenArticuloDao;
    private final EmpresaUsuarioDao empresaUsuarioDao;
    private final EmpresaDao empresaDao;
    private final ConfiguracionLocalTabletDao configuracionLocalTabletDao;
    private final ArticuloUbicacionDao articuloUbicacionDao;
    private final BoxDao boxDao;
    private final ReferenciaUbicacionBoxDao referenciaUbicacionBoxDao;
    private final metavendedorclienteDao metavendedorclienteDao;
    private final ClienteProductoDao clienteProductoDao;
    private final MetaVendedorDao metaVendedorDao;
    private final FormaPagoDetDao formaPagoDetDao;
    private final ClientePinDao clientePinDao;
    private final DescuentoArticuloDao descuentoArticuloDao;
    private final LocalidadVentacabDao localidadVentacabDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productoDaoConfig = daoConfigMap.get(ProductoDao.class).clone();
        productoDaoConfig.initIdentityScope(type);

        datosGeneralesEmpresaDaoConfig = daoConfigMap.get(DatosGeneralesEmpresaDao.class).clone();
        datosGeneralesEmpresaDaoConfig.initIdentityScope(type);

        facturaCabDaoConfig = daoConfigMap.get(FacturaCabDao.class).clone();
        facturaCabDaoConfig.initIdentityScope(type);

        coleccionDaoConfig = daoConfigMap.get(ColeccionDao.class).clone();
        coleccionDaoConfig.initIdentityScope(type);

        usuarioProductoDaoConfig = daoConfigMap.get(UsuarioProductoDao.class).clone();
        usuarioProductoDaoConfig.initIdentityScope(type);

        coleccionEmbarqueDaoConfig = daoConfigMap.get(ColeccionEmbarqueDao.class).clone();
        coleccionEmbarqueDaoConfig.initIdentityScope(type);

        coleccionProductoDaoConfig = daoConfigMap.get(ColeccionProductoDao.class).clone();
        coleccionProductoDaoConfig.initIdentityScope(type);

        usuarioDaoConfig = daoConfigMap.get(UsuarioDao.class).clone();
        usuarioDaoConfig.initIdentityScope(type);

        clienteDaoConfig = daoConfigMap.get(ClienteDao.class).clone();
        clienteDaoConfig.initIdentityScope(type);

        cliente2DaoConfig = daoConfigMap.get(Cliente2Dao.class).clone();
        cliente2DaoConfig.initIdentityScope(type);

        articuloDaoConfig = daoConfigMap.get(ArticuloDao.class).clone();
        articuloDaoConfig.initIdentityScope(type);

        articuloHistoricoVentaDaoConfig = daoConfigMap.get(ArticuloHistoricoVentaDao.class).clone();
        articuloHistoricoVentaDaoConfig.initIdentityScope(type);

        formaPagoDaoConfig = daoConfigMap.get(FormaPagoDao.class).clone();
        formaPagoDaoConfig.initIdentityScope(type);

        referenciaDaoConfig = daoConfigMap.get(ReferenciaDao.class).clone();
        referenciaDaoConfig.initIdentityScope(type);

        clienteFidelidadDaoConfig = daoConfigMap.get(ClienteFidelidadDao.class).clone();
        clienteFidelidadDaoConfig.initIdentityScope(type);

        ventaCabDaoConfig = daoConfigMap.get(VentaCabDao.class).clone();
        ventaCabDaoConfig.initIdentityScope(type);

        ventaDetDaoConfig = daoConfigMap.get(VentaDetDao.class).clone();
        ventaDetDaoConfig.initIdentityScope(type);

        tipoClienteLogDaoConfig = daoConfigMap.get(TipoClienteLogDao.class).clone();
        tipoClienteLogDaoConfig.initIdentityScope(type);

        clienteLogDaoConfig = daoConfigMap.get(ClienteLogDao.class).clone();
        clienteLogDaoConfig.initIdentityScope(type);

        estadoAplicacionDaoConfig = daoConfigMap.get(EstadoAplicacionDao.class).clone();
        estadoAplicacionDaoConfig.initIdentityScope(type);

        familiaDaoConfig = daoConfigMap.get(FamiliaDao.class).clone();
        familiaDaoConfig.initIdentityScope(type);

        tipoPersonaDaoConfig = daoConfigMap.get(TipoPersonaDao.class).clone();
        tipoPersonaDaoConfig.initIdentityScope(type);

        tipoDocumentoDaoConfig = daoConfigMap.get(TipoDocumentoDao.class).clone();
        tipoDocumentoDaoConfig.initIdentityScope(type);

        tipoClienteDaoConfig = daoConfigMap.get(TipoClienteDao.class).clone();
        tipoClienteDaoConfig.initIdentityScope(type);

        localidadDaoConfig = daoConfigMap.get(LocalidadDao.class).clone();
        localidadDaoConfig.initIdentityScope(type);

        regionDaoConfig = daoConfigMap.get(RegionDao.class).clone();
        regionDaoConfig.initIdentityScope(type);

        zonaDaoConfig = daoConfigMap.get(ZonaDao.class).clone();
        zonaDaoConfig.initIdentityScope(type);

        rubroDaoConfig = daoConfigMap.get(RubroDao.class).clone();
        rubroDaoConfig.initIdentityScope(type);

        barrioDaoConfig = daoConfigMap.get(BarrioDao.class).clone();
        barrioDaoConfig.initIdentityScope(type);

        lineaArticuloDaoConfig = daoConfigMap.get(LineaArticuloDao.class).clone();
        lineaArticuloDaoConfig.initIdentityScope(type);

        ultimaVentaDaoConfig = daoConfigMap.get(UltimaVentaDao.class).clone();
        ultimaVentaDaoConfig.initIdentityScope(type);

        programaVisitaDaoConfig = daoConfigMap.get(ProgramaVisitaDao.class).clone();
        programaVisitaDaoConfig.initIdentityScope(type);

        grupoLineaArticuloDaoConfig = daoConfigMap.get(GrupoLineaArticuloDao.class).clone();
        grupoLineaArticuloDaoConfig.initIdentityScope(type);

        estadoPedidoHechoDaoConfig = daoConfigMap.get(EstadoPedidoHechoDao.class).clone();
        estadoPedidoHechoDaoConfig.initIdentityScope(type);

        promedioPorColeccionDaoConfig = daoConfigMap.get(PromedioPorColeccionDao.class).clone();
        promedioPorColeccionDaoConfig.initIdentityScope(type);

        promocionDaoConfig = daoConfigMap.get(PromocionDao.class).clone();
        promocionDaoConfig.initIdentityScope(type);

        configuracionRemotaTabletDaoConfig = daoConfigMap.get(ConfiguracionRemotaTabletDao.class).clone();
        configuracionRemotaTabletDaoConfig.initIdentityScope(type);

        escalaDaoConfig = daoConfigMap.get(EscalaDao.class).clone();
        escalaDaoConfig.initIdentityScope(type);

        grupoMultiplicadorDaoConfig = daoConfigMap.get(GrupoMultiplicadorDao.class).clone();
        grupoMultiplicadorDaoConfig.initIdentityScope(type);

        productMigradoFabricaDaoConfig = daoConfigMap.get(ProductMigradoFabricaDao.class).clone();
        productMigradoFabricaDaoConfig.initIdentityScope(type);

        imagenArticuloDaoConfig = daoConfigMap.get(ImagenArticuloDao.class).clone();
        imagenArticuloDaoConfig.initIdentityScope(type);

        empresaUsuarioDaoConfig = daoConfigMap.get(EmpresaUsuarioDao.class).clone();
        empresaUsuarioDaoConfig.initIdentityScope(type);

        empresaDaoConfig = daoConfigMap.get(EmpresaDao.class).clone();
        empresaDaoConfig.initIdentityScope(type);

        configuracionLocalTabletDaoConfig = daoConfigMap.get(ConfiguracionLocalTabletDao.class).clone();
        configuracionLocalTabletDaoConfig.initIdentityScope(type);

        articuloUbicacionDaoConfig = daoConfigMap.get(ArticuloUbicacionDao.class).clone();
        articuloUbicacionDaoConfig.initIdentityScope(type);

        boxDaoConfig = daoConfigMap.get(BoxDao.class).clone();
        boxDaoConfig.initIdentityScope(type);

        referenciaUbicacionBoxDaoConfig = daoConfigMap.get(ReferenciaUbicacionBoxDao.class).clone();
        referenciaUbicacionBoxDaoConfig.initIdentityScope(type);

        metavendedorclienteDaoConfig = daoConfigMap.get(metavendedorclienteDao.class).clone();
        metavendedorclienteDaoConfig.initIdentityScope(type);

        clienteProductoDaoConfig = daoConfigMap.get(ClienteProductoDao.class).clone();
        clienteProductoDaoConfig.initIdentityScope(type);

        metaVendedorDaoConfig = daoConfigMap.get(MetaVendedorDao.class).clone();
        metaVendedorDaoConfig.initIdentityScope(type);

        formaPagoDetDaoConfig = daoConfigMap.get(FormaPagoDetDao.class).clone();
        formaPagoDetDaoConfig.initIdentityScope(type);

        clientePinDaoConfig = daoConfigMap.get(ClientePinDao.class).clone();
        clientePinDaoConfig.initIdentityScope(type);

        descuentoArticuloDaoConfig = daoConfigMap.get(DescuentoArticuloDao.class).clone();
        descuentoArticuloDaoConfig.initIdentityScope(type);

        localidadVentacabDaoConfig = daoConfigMap.get(LocalidadVentacabDao.class).clone();
        localidadVentacabDaoConfig.initIdentityScope(type);

        productoDao = new ProductoDao(productoDaoConfig, this);
        datosGeneralesEmpresaDao = new DatosGeneralesEmpresaDao(datosGeneralesEmpresaDaoConfig, this);
        facturaCabDao = new FacturaCabDao(facturaCabDaoConfig, this);
        coleccionDao = new ColeccionDao(coleccionDaoConfig, this);
        usuarioProductoDao = new UsuarioProductoDao(usuarioProductoDaoConfig, this);
        coleccionEmbarqueDao = new ColeccionEmbarqueDao(coleccionEmbarqueDaoConfig, this);
        coleccionProductoDao = new ColeccionProductoDao(coleccionProductoDaoConfig, this);
        usuarioDao = new UsuarioDao(usuarioDaoConfig, this);
        clienteDao = new ClienteDao(clienteDaoConfig, this);
        cliente2Dao = new Cliente2Dao(cliente2DaoConfig, this);
        articuloDao = new ArticuloDao(articuloDaoConfig, this);
        articuloHistoricoVentaDao = new ArticuloHistoricoVentaDao(articuloHistoricoVentaDaoConfig, this);
        formaPagoDao = new FormaPagoDao(formaPagoDaoConfig, this);
        referenciaDao = new ReferenciaDao(referenciaDaoConfig, this);
        clienteFidelidadDao = new ClienteFidelidadDao(clienteFidelidadDaoConfig, this);
        ventaCabDao = new VentaCabDao(ventaCabDaoConfig, this);
        ventaDetDao = new VentaDetDao(ventaDetDaoConfig, this);
        tipoClienteLogDao = new TipoClienteLogDao(tipoClienteLogDaoConfig, this);
        clienteLogDao = new ClienteLogDao(clienteLogDaoConfig, this);
        estadoAplicacionDao = new EstadoAplicacionDao(estadoAplicacionDaoConfig, this);
        familiaDao = new FamiliaDao(familiaDaoConfig, this);
        tipoPersonaDao = new TipoPersonaDao(tipoPersonaDaoConfig, this);
        tipoDocumentoDao = new TipoDocumentoDao(tipoDocumentoDaoConfig, this);
        tipoClienteDao = new TipoClienteDao(tipoClienteDaoConfig, this);
        localidadDao = new LocalidadDao(localidadDaoConfig, this);
        regionDao = new RegionDao(regionDaoConfig, this);
        zonaDao = new ZonaDao(zonaDaoConfig, this);
        rubroDao = new RubroDao(rubroDaoConfig, this);
        barrioDao = new BarrioDao(barrioDaoConfig, this);
        lineaArticuloDao = new LineaArticuloDao(lineaArticuloDaoConfig, this);
        ultimaVentaDao = new UltimaVentaDao(ultimaVentaDaoConfig, this);
        programaVisitaDao = new ProgramaVisitaDao(programaVisitaDaoConfig, this);
        grupoLineaArticuloDao = new GrupoLineaArticuloDao(grupoLineaArticuloDaoConfig, this);
        estadoPedidoHechoDao = new EstadoPedidoHechoDao(estadoPedidoHechoDaoConfig, this);
        promedioPorColeccionDao = new PromedioPorColeccionDao(promedioPorColeccionDaoConfig, this);
        promocionDao = new PromocionDao(promocionDaoConfig, this);
        configuracionRemotaTabletDao = new ConfiguracionRemotaTabletDao(configuracionRemotaTabletDaoConfig, this);
        escalaDao = new EscalaDao(escalaDaoConfig, this);
        grupoMultiplicadorDao = new GrupoMultiplicadorDao(grupoMultiplicadorDaoConfig, this);
        productMigradoFabricaDao = new ProductMigradoFabricaDao(productMigradoFabricaDaoConfig, this);
        imagenArticuloDao = new ImagenArticuloDao(imagenArticuloDaoConfig, this);
        empresaUsuarioDao = new EmpresaUsuarioDao(empresaUsuarioDaoConfig, this);
        empresaDao = new EmpresaDao(empresaDaoConfig, this);
        configuracionLocalTabletDao = new ConfiguracionLocalTabletDao(configuracionLocalTabletDaoConfig, this);
        articuloUbicacionDao = new ArticuloUbicacionDao(articuloUbicacionDaoConfig, this);
        boxDao = new BoxDao(boxDaoConfig, this);
        referenciaUbicacionBoxDao = new ReferenciaUbicacionBoxDao(referenciaUbicacionBoxDaoConfig, this);
        metavendedorclienteDao = new metavendedorclienteDao(metavendedorclienteDaoConfig, this);
        clienteProductoDao = new ClienteProductoDao(clienteProductoDaoConfig, this);
        metaVendedorDao = new MetaVendedorDao(metaVendedorDaoConfig, this);
        formaPagoDetDao = new FormaPagoDetDao(formaPagoDetDaoConfig, this);
        clientePinDao = new ClientePinDao(clientePinDaoConfig, this);
        descuentoArticuloDao = new DescuentoArticuloDao(descuentoArticuloDaoConfig, this);
        localidadVentacabDao = new LocalidadVentacabDao(localidadVentacabDaoConfig, this);

        registerDao(Producto.class, productoDao);
        registerDao(DatosGeneralesEmpresa.class, datosGeneralesEmpresaDao);
        registerDao(FacturaCab.class, facturaCabDao);
        registerDao(Coleccion.class, coleccionDao);
        registerDao(UsuarioProducto.class, usuarioProductoDao);
        registerDao(ColeccionEmbarque.class, coleccionEmbarqueDao);
        registerDao(ColeccionProducto.class, coleccionProductoDao);
        registerDao(Usuario.class, usuarioDao);
        registerDao(Cliente.class, clienteDao);
        registerDao(Cliente2.class, cliente2Dao);
        registerDao(Articulo.class, articuloDao);
        registerDao(ArticuloHistoricoVenta.class, articuloHistoricoVentaDao);
        registerDao(FormaPago.class, formaPagoDao);
        registerDao(Referencia.class, referenciaDao);
        registerDao(ClienteFidelidad.class, clienteFidelidadDao);
        registerDao(VentaCab.class, ventaCabDao);
        registerDao(VentaDet.class, ventaDetDao);
        registerDao(TipoClienteLog.class, tipoClienteLogDao);
        registerDao(ClienteLog.class, clienteLogDao);
        registerDao(EstadoAplicacion.class, estadoAplicacionDao);
        registerDao(Familia.class, familiaDao);
        registerDao(TipoPersona.class, tipoPersonaDao);
        registerDao(TipoDocumento.class, tipoDocumentoDao);
        registerDao(TipoCliente.class, tipoClienteDao);
        registerDao(Localidad.class, localidadDao);
        registerDao(Region.class, regionDao);
        registerDao(Zona.class, zonaDao);
        registerDao(Rubro.class, rubroDao);
        registerDao(Barrio.class, barrioDao);
        registerDao(LineaArticulo.class, lineaArticuloDao);
        registerDao(UltimaVenta.class, ultimaVentaDao);
        registerDao(ProgramaVisita.class, programaVisitaDao);
        registerDao(GrupoLineaArticulo.class, grupoLineaArticuloDao);
        registerDao(EstadoPedidoHecho.class, estadoPedidoHechoDao);
        registerDao(PromedioPorColeccion.class, promedioPorColeccionDao);
        registerDao(Promocion.class, promocionDao);
        registerDao(ConfiguracionRemotaTablet.class, configuracionRemotaTabletDao);
        registerDao(Escala.class, escalaDao);
        registerDao(GrupoMultiplicador.class, grupoMultiplicadorDao);
        registerDao(ProductMigradoFabrica.class, productMigradoFabricaDao);
        registerDao(ImagenArticulo.class, imagenArticuloDao);
        registerDao(EmpresaUsuario.class, empresaUsuarioDao);
        registerDao(Empresa.class, empresaDao);
        registerDao(ConfiguracionLocalTablet.class, configuracionLocalTabletDao);
        registerDao(ArticuloUbicacion.class, articuloUbicacionDao);
        registerDao(Box.class, boxDao);
        registerDao(ReferenciaUbicacionBox.class, referenciaUbicacionBoxDao);
        registerDao(metavendedorcliente.class, metavendedorclienteDao);
        registerDao(ClienteProducto.class, clienteProductoDao);
        registerDao(MetaVendedor.class, metaVendedorDao);
        registerDao(FormaPagoDet.class, formaPagoDetDao);
        registerDao(ClientePin.class, clientePinDao);
        registerDao(DescuentoArticulo.class, descuentoArticuloDao);
        registerDao(LocalidadVentacab.class, localidadVentacabDao);
    }

    public void clear() {
        productoDaoConfig.getIdentityScope().clear();
        datosGeneralesEmpresaDaoConfig.getIdentityScope().clear();
        facturaCabDaoConfig.getIdentityScope().clear();
        coleccionDaoConfig.getIdentityScope().clear();
        usuarioProductoDaoConfig.getIdentityScope().clear();
        coleccionEmbarqueDaoConfig.getIdentityScope().clear();
        coleccionProductoDaoConfig.getIdentityScope().clear();
        usuarioDaoConfig.getIdentityScope().clear();
        clienteDaoConfig.getIdentityScope().clear();
        cliente2DaoConfig.getIdentityScope().clear();
        articuloDaoConfig.getIdentityScope().clear();
        articuloHistoricoVentaDaoConfig.getIdentityScope().clear();
        formaPagoDaoConfig.getIdentityScope().clear();
        referenciaDaoConfig.getIdentityScope().clear();
        clienteFidelidadDaoConfig.getIdentityScope().clear();
        ventaCabDaoConfig.getIdentityScope().clear();
        ventaDetDaoConfig.getIdentityScope().clear();
        tipoClienteLogDaoConfig.getIdentityScope().clear();
        clienteLogDaoConfig.getIdentityScope().clear();
        estadoAplicacionDaoConfig.getIdentityScope().clear();
        familiaDaoConfig.getIdentityScope().clear();
        tipoPersonaDaoConfig.getIdentityScope().clear();
        tipoDocumentoDaoConfig.getIdentityScope().clear();
        tipoClienteDaoConfig.getIdentityScope().clear();
        localidadDaoConfig.getIdentityScope().clear();
        regionDaoConfig.getIdentityScope().clear();
        zonaDaoConfig.getIdentityScope().clear();
        rubroDaoConfig.getIdentityScope().clear();
        barrioDaoConfig.getIdentityScope().clear();
        lineaArticuloDaoConfig.getIdentityScope().clear();
        ultimaVentaDaoConfig.getIdentityScope().clear();
        programaVisitaDaoConfig.getIdentityScope().clear();
        grupoLineaArticuloDaoConfig.getIdentityScope().clear();
        estadoPedidoHechoDaoConfig.getIdentityScope().clear();
        promedioPorColeccionDaoConfig.getIdentityScope().clear();
        promocionDaoConfig.getIdentityScope().clear();
        configuracionRemotaTabletDaoConfig.getIdentityScope().clear();
        escalaDaoConfig.getIdentityScope().clear();
        grupoMultiplicadorDaoConfig.getIdentityScope().clear();
        productMigradoFabricaDaoConfig.getIdentityScope().clear();
        imagenArticuloDaoConfig.getIdentityScope().clear();
        empresaUsuarioDaoConfig.getIdentityScope().clear();
        empresaDaoConfig.getIdentityScope().clear();
        configuracionLocalTabletDaoConfig.getIdentityScope().clear();
        articuloUbicacionDaoConfig.getIdentityScope().clear();
        boxDaoConfig.getIdentityScope().clear();
        referenciaUbicacionBoxDaoConfig.getIdentityScope().clear();
        metavendedorclienteDaoConfig.getIdentityScope().clear();
        clienteProductoDaoConfig.getIdentityScope().clear();
        metaVendedorDaoConfig.getIdentityScope().clear();
        formaPagoDetDaoConfig.getIdentityScope().clear();
        clientePinDaoConfig.getIdentityScope().clear();
        descuentoArticuloDaoConfig.getIdentityScope().clear();
        localidadVentacabDaoConfig.getIdentityScope().clear();
    }

    public ProductoDao getProductoDao() {
        return productoDao;
    }

    public DatosGeneralesEmpresaDao getDatosGeneralesEmpresaDao() {
        return datosGeneralesEmpresaDao;
    }

    public FacturaCabDao getFacturaCabDao() {
        return facturaCabDao;
    }

    public ColeccionDao getColeccionDao() {
        return coleccionDao;
    }

    public UsuarioProductoDao getUsuarioProductoDao() {
        return usuarioProductoDao;
    }

    public ColeccionEmbarqueDao getColeccionEmbarqueDao() {
        return coleccionEmbarqueDao;
    }

    public ColeccionProductoDao getColeccionProductoDao() {
        return coleccionProductoDao;
    }

    public UsuarioDao getUsuarioDao() {
        return usuarioDao;
    }

    public ClienteDao getClienteDao() {
        return clienteDao;
    }

    public Cliente2Dao getCliente2Dao() {
        return cliente2Dao;
    }

    public ArticuloDao getArticuloDao() {
        return articuloDao;
    }

    public ArticuloHistoricoVentaDao getArticuloHistoricoVentaDao() {
        return articuloHistoricoVentaDao;
    }

    public FormaPagoDao getFormaPagoDao() {
        return formaPagoDao;
    }

    public ReferenciaDao getReferenciaDao() {
        return referenciaDao;
    }

    public ClienteFidelidadDao getClienteFidelidadDao() {
        return clienteFidelidadDao;
    }

    public VentaCabDao getVentaCabDao() {
        return ventaCabDao;
    }

    public VentaDetDao getVentaDetDao() {
        return ventaDetDao;
    }

    public TipoClienteLogDao getTipoClienteLogDao() {
        return tipoClienteLogDao;
    }

    public ClienteLogDao getClienteLogDao() {
        return clienteLogDao;
    }

    public EstadoAplicacionDao getEstadoAplicacionDao() {
        return estadoAplicacionDao;
    }

    public FamiliaDao getFamiliaDao() {
        return familiaDao;
    }

    public TipoPersonaDao getTipoPersonaDao() {
        return tipoPersonaDao;
    }

    public TipoDocumentoDao getTipoDocumentoDao() {
        return tipoDocumentoDao;
    }

    public TipoClienteDao getTipoClienteDao() {
        return tipoClienteDao;
    }

    public LocalidadDao getLocalidadDao() {
        return localidadDao;
    }

    public RegionDao getRegionDao() {
        return regionDao;
    }

    public ZonaDao getZonaDao() {
        return zonaDao;
    }

    public RubroDao getRubroDao() {
        return rubroDao;
    }

    public BarrioDao getBarrioDao() {
        return barrioDao;
    }

    public LineaArticuloDao getLineaArticuloDao() {
        return lineaArticuloDao;
    }

    public UltimaVentaDao getUltimaVentaDao() {
        return ultimaVentaDao;
    }

    public ProgramaVisitaDao getProgramaVisitaDao() {
        return programaVisitaDao;
    }

    public GrupoLineaArticuloDao getGrupoLineaArticuloDao() {
        return grupoLineaArticuloDao;
    }

    public EstadoPedidoHechoDao getEstadoPedidoHechoDao() {
        return estadoPedidoHechoDao;
    }

    public PromedioPorColeccionDao getPromedioPorColeccionDao() {
        return promedioPorColeccionDao;
    }

    public PromocionDao getPromocionDao() {
        return promocionDao;
    }

    public ConfiguracionRemotaTabletDao getConfiguracionRemotaTabletDao() {
        return configuracionRemotaTabletDao;
    }

    public EscalaDao getEscalaDao() {
        return escalaDao;
    }

    public GrupoMultiplicadorDao getGrupoMultiplicadorDao() {
        return grupoMultiplicadorDao;
    }

    public ProductMigradoFabricaDao getProductMigradoFabricaDao() {
        return productMigradoFabricaDao;
    }

    public ImagenArticuloDao getImagenArticuloDao() {
        return imagenArticuloDao;
    }

    public EmpresaUsuarioDao getEmpresaUsuarioDao() {
        return empresaUsuarioDao;
    }

    public EmpresaDao getEmpresaDao() {
        return empresaDao;
    }

    public ConfiguracionLocalTabletDao getConfiguracionLocalTabletDao() {
        return configuracionLocalTabletDao;
    }

    public ArticuloUbicacionDao getArticuloUbicacionDao() {
        return articuloUbicacionDao;
    }

    public BoxDao getBoxDao() {
        return boxDao;
    }

    public ReferenciaUbicacionBoxDao getReferenciaUbicacionBoxDao() {
        return referenciaUbicacionBoxDao;
    }

    public metavendedorclienteDao getMetavendedorclienteDao() {
        return metavendedorclienteDao;
    }

    public ClienteProductoDao getClienteProductoDao() {
        return clienteProductoDao;
    }

    public MetaVendedorDao getMetaVendedorDao() {
        return metaVendedorDao;
    }

    public FormaPagoDetDao getFormaPagoDetDao() {
        return formaPagoDetDao;
    }

    public ClientePinDao getClientePinDao() {
        return clientePinDao;
    }

    public DescuentoArticuloDao getDescuentoArticuloDao() {
        return descuentoArticuloDao;
    }

    public LocalidadVentacabDao getLocalidadVentacabDao() {
        return localidadVentacabDao;
    }

}
