package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DATOS_GENERALES_EMPRESA".
 */
public class DatosGeneralesEmpresa implements java.io.Serializable {

    private Long iddatogeneral;
    /** Not-null value. */
    private String campo;
    private String dato;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DatosGeneralesEmpresa() {
    }

    public DatosGeneralesEmpresa(Long iddatogeneral) {
        this.iddatogeneral = iddatogeneral;
    }

    public DatosGeneralesEmpresa(Long iddatogeneral, String campo, String dato) {
        this.iddatogeneral = iddatogeneral;
        this.campo = campo;
        this.dato = dato;
    }

    public Long getIddatogeneral() {
        return iddatogeneral;
    }

    public void setIddatogeneral(Long iddatogeneral) {
        this.iddatogeneral = iddatogeneral;
    }

    /** Not-null value. */
    public String getCampo() {
        return campo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCampo(String campo) {
        this.campo = campo;
    }

    public String getDato() {
        return dato;
    }

    public void setDato(String dato) {
        this.dato = dato;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
