package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EMPRESA_USUARIO".
 */
public class EmpresaUsuario {

    private Long idusuarioempresa;
    private long idusuario;
    private long idempresa;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public EmpresaUsuario() {
    }

    public EmpresaUsuario(Long idusuarioempresa) {
        this.idusuarioempresa = idusuarioempresa;
    }

    public EmpresaUsuario(Long idusuarioempresa, long idusuario, long idempresa) {
        this.idusuarioempresa = idusuarioempresa;
        this.idusuario = idusuario;
        this.idempresa = idempresa;
    }

    public Long getIdusuarioempresa() {
        return idusuarioempresa;
    }

    public void setIdusuarioempresa(Long idusuarioempresa) {
        this.idusuarioempresa = idusuarioempresa;
    }

    public long getIdusuario() {
        return idusuario;
    }

    public void setIdusuario(long idusuario) {
        this.idusuario = idusuario;
    }

    public long getIdempresa() {
        return idempresa;
    }

    public void setIdempresa(long idempresa) {
        this.idempresa = idempresa;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
