package empresa.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import empresa.dao.Empresa;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EMPRESA".
*/
public class EmpresaDao extends AbstractDao<Empresa, Long> {

    public static final String TABLENAME = "EMPRESA";

    /**
     * Properties of entity Empresa.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Idempresa = new Property(0, Long.class, "idempresa", true, "IDEMPRESA");
        public final static Property Descripcion = new Property(1, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Abreviacion = new Property(2, String.class, "abreviacion", false, "ABREVIACION");
    };


    public EmpresaDao(DaoConfig config) {
        super(config);
    }

    public EmpresaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'EMPRESA' (" + //
                "'IDEMPRESA' INTEGER PRIMARY KEY ," + // 0: idempresa
                "'DESCRIPCION' TEXT NOT NULL ," + // 1: descripcion
                "'ABREVIACION' TEXT);"); // 2: abreviacion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'EMPRESA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Empresa entity) {
        stmt.clearBindings();

        Long idempresa = entity.getIdempresa();
        if (idempresa != null) {
            stmt.bindLong(1, idempresa);
        }
        stmt.bindString(2, entity.getDescripcion());

        String abreviacion = entity.getAbreviacion();
        if (abreviacion != null) {
            stmt.bindString(3, abreviacion);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public Empresa readEntity(Cursor cursor, int offset) {
        Empresa entity = new Empresa( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idempresa
                cursor.getString(offset + 1), // descripcion
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // abreviacion
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Empresa entity, int offset) {
        entity.setIdempresa(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescripcion(cursor.getString(offset + 1));
        entity.setAbreviacion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Empresa entity, long rowId) {
        entity.setIdempresa(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(Empresa entity) {
        if(entity != null) {
            return entity.getIdempresa();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
