package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ESCALA".
 */
public class Escala {

    private Long idescala;
    private long idoficial;
    private long idcoleccion;
    private long idproducto;
    private long plazodesde;
    private long plazohasta;
    private Long cantidaddesde;
    private Long cantidahasta;
    private java.util.Date fechadesde;
    private java.util.Date fechahasta;
    private double descuentodesde;
    private double descuentohasta;
    private double comision;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Escala() {
    }

    public Escala(Long idescala) {
        this.idescala = idescala;
    }

    public Escala(Long idescala, long idoficial, long idcoleccion, long idproducto, long plazodesde, long plazohasta, Long cantidaddesde, Long cantidahasta, java.util.Date fechadesde, java.util.Date fechahasta, double descuentodesde, double descuentohasta, double comision) {
        this.idescala = idescala;
        this.idoficial = idoficial;
        this.idcoleccion = idcoleccion;
        this.idproducto = idproducto;
        this.plazodesde = plazodesde;
        this.plazohasta = plazohasta;
        this.cantidaddesde = cantidaddesde;
        this.cantidahasta = cantidahasta;
        this.fechadesde = fechadesde;
        this.fechahasta = fechahasta;
        this.descuentodesde = descuentodesde;
        this.descuentohasta = descuentohasta;
        this.comision = comision;
    }

    public Long getIdescala() {
        return idescala;
    }

    public void setIdescala(Long idescala) {
        this.idescala = idescala;
    }

    public long getIdoficial() {
        return idoficial;
    }

    public void setIdoficial(long idoficial) {
        this.idoficial = idoficial;
    }

    public long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    public long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(long idproducto) {
        this.idproducto = idproducto;
    }

    public long getPlazodesde() {
        return plazodesde;
    }

    public void setPlazodesde(long plazodesde) {
        this.plazodesde = plazodesde;
    }

    public long getPlazohasta() {
        return plazohasta;
    }

    public void setPlazohasta(long plazohasta) {
        this.plazohasta = plazohasta;
    }

    public Long getCantidaddesde() {
        return cantidaddesde;
    }

    public void setCantidaddesde(Long cantidaddesde) {
        this.cantidaddesde = cantidaddesde;
    }

    public Long getCantidahasta() {
        return cantidahasta;
    }

    public void setCantidahasta(Long cantidahasta) {
        this.cantidahasta = cantidahasta;
    }

    public java.util.Date getFechadesde() {
        return fechadesde;
    }

    public void setFechadesde(java.util.Date fechadesde) {
        this.fechadesde = fechadesde;
    }

    public java.util.Date getFechahasta() {
        return fechahasta;
    }

    public void setFechahasta(java.util.Date fechahasta) {
        this.fechahasta = fechahasta;
    }

    public double getDescuentodesde() {
        return descuentodesde;
    }

    public void setDescuentodesde(double descuentodesde) {
        this.descuentodesde = descuentodesde;
    }

    public double getDescuentohasta() {
        return descuentohasta;
    }

    public void setDescuentohasta(double descuentohasta) {
        this.descuentohasta = descuentohasta;
    }

    public double getComision() {
        return comision;
    }

    public void setComision(double comision) {
        this.comision = comision;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
