package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ESTADO_PEDIDO_HECHO".
 */
public class EstadoPedidoHecho implements java.io.Serializable {

    private Long idventacab;
    private long idestadoventa;
    private long idoficial;
    private long idproducto;
    private long idcoleccion;
    private long idcliente;
    private long idformapago;
    private long cantidadtotal;
    private Long idembarquecab;
    private double importe;
    private Double promediodescuento;
    private String observacion;
    private String condicion;
    /** Not-null value. */
    private java.util.Date fechaoperacion;
    /** Not-null value. */
    private java.util.Date fecha;
    private String origen;
    private String tipo;
    private java.util.Date fechapactoentrega;

    // KEEP FIELDS - put your custom fields here
    private String searchMetadata;
    // KEEP FIELDS END

    public EstadoPedidoHecho() {
    }

    public EstadoPedidoHecho(Long idventacab) {
        this.idventacab = idventacab;
    }

    public EstadoPedidoHecho(Long idventacab, long idestadoventa, long idoficial, long idproducto, long idcoleccion, long idcliente, long idformapago, long cantidadtotal, Long idembarquecab, double importe, Double promediodescuento, String observacion, String condicion, java.util.Date fechaoperacion, java.util.Date fecha, String origen, String tipo, java.util.Date fechapactoentrega) {
        this.idventacab = idventacab;
        this.idestadoventa = idestadoventa;
        this.idoficial = idoficial;
        this.idproducto = idproducto;
        this.idcoleccion = idcoleccion;
        this.idcliente = idcliente;
        this.idformapago = idformapago;
        this.cantidadtotal = cantidadtotal;
        this.idembarquecab = idembarquecab;
        this.importe = importe;
        this.promediodescuento = promediodescuento;
        this.observacion = observacion;
        this.condicion = condicion;
        this.fechaoperacion = fechaoperacion;
        this.fecha = fecha;
        this.origen = origen;
        this.tipo = tipo;
        this.fechapactoentrega = fechapactoentrega;
    }

    public Long getIdventacab() {
        return idventacab;
    }

    public void setIdventacab(Long idventacab) {
        this.idventacab = idventacab;
    }

    public long getIdestadoventa() {
        return idestadoventa;
    }

    public void setIdestadoventa(long idestadoventa) {
        this.idestadoventa = idestadoventa;
    }

    public long getIdoficial() {
        return idoficial;
    }

    public void setIdoficial(long idoficial) {
        this.idoficial = idoficial;
    }

    public long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(long idproducto) {
        this.idproducto = idproducto;
    }

    public long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    public long getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(long idcliente) {
        this.idcliente = idcliente;
    }

    public long getIdformapago() {
        return idformapago;
    }

    public void setIdformapago(long idformapago) {
        this.idformapago = idformapago;
    }

    public long getCantidadtotal() {
        return cantidadtotal;
    }

    public void setCantidadtotal(long cantidadtotal) {
        this.cantidadtotal = cantidadtotal;
    }

    public Long getIdembarquecab() {
        return idembarquecab;
    }

    public void setIdembarquecab(Long idembarquecab) {
        this.idembarquecab = idembarquecab;
    }

    public double getImporte() {
        return importe;
    }

    public void setImporte(double importe) {
        this.importe = importe;
    }

    public Double getPromediodescuento() {
        return promediodescuento;
    }

    public void setPromediodescuento(Double promediodescuento) {
        this.promediodescuento = promediodescuento;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public String getCondicion() {
        return condicion;
    }

    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }

    /** Not-null value. */
    public java.util.Date getFechaoperacion() {
        return fechaoperacion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaoperacion(java.util.Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }

    /** Not-null value. */
    public java.util.Date getFecha() {
        return fecha;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    public String getOrigen() {
        return origen;
    }

    public void setOrigen(String origen) {
        this.origen = origen;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public java.util.Date getFechapactoentrega() {
        return fechapactoentrega;
    }

    public void setFechapactoentrega(java.util.Date fechapactoentrega) {
        this.fechapactoentrega = fechapactoentrega;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "EstadoPedidoHeho: idventacab" +  getIdventacab() + ",  idestadoventa:" + getIdestadoventa() ;
    }


    public String getSearchMetadata() {

        return searchMetadata;
    }

    public void setSearchMetadata(String searchMetadata) {
        this.searchMetadata = searchMetadata;
    }
    // KEEP METHODS END

}
