package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FAMILIA".
 */
public class Familia {

    private Long idfamilia;
    /** Not-null value. */
    private String descripcion;

    // KEEP FIELDS - put your custom fields here
    //linea modificada para que se pueda cargar dupe
    //public static final long ID_FAMILIA_CALZADO = 9;

    public static final long ID_FAMILIA_CALZADO = 150;
    // KEEP FIELDS END

    public Familia() {
    }

    public Familia(Long idfamilia) {
        this.idfamilia = idfamilia;
    }

    public Familia(Long idfamilia, String descripcion) {
        this.idfamilia = idfamilia;
        this.descripcion = descripcion;
    }

    public Long getIdfamilia() {
        return idfamilia;
    }

    public void setIdfamilia(Long idfamilia) {
        this.idfamilia = idfamilia;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
