package empresa.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import empresa.dao.GrupoMultiplicador;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GRUPO_MULTIPLICADOR".
*/
public class GrupoMultiplicadorDao extends AbstractDao<GrupoMultiplicador, Long> {

    public static final String TABLENAME = "GRUPO_MULTIPLICADOR";

    /**
     * Properties of entity GrupoMultiplicador.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Idgrupo = new Property(0, Long.class, "idgrupo", true, "IDGRUPO");
        public final static Property Multiplicador = new Property(1, Long.class, "multiplicador", false, "MULTIPLICADOR");
        public final static Property Descripcion = new Property(2, String.class, "descripcion", false, "DESCRIPCION");
    };


    public GrupoMultiplicadorDao(DaoConfig config) {
        super(config);
    }

    public GrupoMultiplicadorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GRUPO_MULTIPLICADOR' (" + //
                "'IDGRUPO' INTEGER PRIMARY KEY ," + // 0: idgrupo
                "'MULTIPLICADOR' INTEGER," + // 1: multiplicador
                "'DESCRIPCION' TEXT NOT NULL );"); // 2: descripcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GRUPO_MULTIPLICADOR'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GrupoMultiplicador entity) {
        stmt.clearBindings();

        Long idgrupo = entity.getIdgrupo();
        if (idgrupo != null) {
            stmt.bindLong(1, idgrupo);
        }

        Long multiplicador = entity.getMultiplicador();
        if (multiplicador != null) {
            stmt.bindLong(2, multiplicador);
        }
        stmt.bindString(3, entity.getDescripcion());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public GrupoMultiplicador readEntity(Cursor cursor, int offset) {
        GrupoMultiplicador entity = new GrupoMultiplicador( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idgrupo
                cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // multiplicador
                cursor.getString(offset + 2) // descripcion
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GrupoMultiplicador entity, int offset) {
        entity.setIdgrupo(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMultiplicador(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDescripcion(cursor.getString(offset + 2));
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GrupoMultiplicador entity, long rowId) {
        entity.setIdgrupo(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(GrupoMultiplicador entity) {
        if(entity != null) {
            return entity.getIdgrupo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
