package empresa.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import empresa.dao.GrupoLineaArticulo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GRUPO_LINEA_ARTICULO".
*/
public class GrupoLineaArticuloDao extends AbstractDao<GrupoLineaArticulo, Long> {

    public static final String TABLENAME = "GRUPO_LINEA_ARTICULO";

    /**
     * Properties of entity GrupoLineaArticulo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Idgrupolineaarticulo = new Property(0, Long.class, "idgrupolineaarticulo", true, "IDGRUPOLINEAARTICULO");
        public final static Property Descripcion = new Property(1, String.class, "descripcion", false, "DESCRIPCION");
    };


    public GrupoLineaArticuloDao(DaoConfig config) {
        super(config);
    }

    public GrupoLineaArticuloDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GRUPO_LINEA_ARTICULO' (" + //
                "'IDGRUPOLINEAARTICULO' INTEGER PRIMARY KEY ," + // 0: idgrupolineaarticulo
                "'DESCRIPCION' TEXT NOT NULL );"); // 1: descripcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GRUPO_LINEA_ARTICULO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GrupoLineaArticulo entity) {
        stmt.clearBindings();

        Long idgrupolineaarticulo = entity.getIdgrupolineaarticulo();
        if (idgrupolineaarticulo != null) {
            stmt.bindLong(1, idgrupolineaarticulo);
        }
        stmt.bindString(2, entity.getDescripcion());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public GrupoLineaArticulo readEntity(Cursor cursor, int offset) {
        GrupoLineaArticulo entity = new GrupoLineaArticulo( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idgrupolineaarticulo
                cursor.getString(offset + 1) // descripcion
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GrupoLineaArticulo entity, int offset) {
        entity.setIdgrupolineaarticulo(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescripcion(cursor.getString(offset + 1));
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GrupoLineaArticulo entity, long rowId) {
        entity.setIdgrupolineaarticulo(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(GrupoLineaArticulo entity) {
        if(entity != null) {
            return entity.getIdgrupolineaarticulo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
