package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LINEA_ARTICULO".
 */
public class LineaArticulo implements java.io.Serializable {

    private Long idlineaarticulo;
    /** Not-null value. */
    private String descripcion;
    private Long idgrupolineaarticulo;
    private Boolean indicadorPermiteDescuento;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LineaArticulo() {
    }

    public LineaArticulo(Long idlineaarticulo) {
        this.idlineaarticulo = idlineaarticulo;
    }

    public LineaArticulo(Long idlineaarticulo, String descripcion, Long idgrupolineaarticulo, Boolean indicadorPermiteDescuento) {
        this.idlineaarticulo = idlineaarticulo;
        this.descripcion = descripcion;
        this.idgrupolineaarticulo = idgrupolineaarticulo;
        this.indicadorPermiteDescuento = indicadorPermiteDescuento;
    }

    public Long getIdlineaarticulo() {
        return idlineaarticulo;
    }

    public void setIdlineaarticulo(Long idlineaarticulo) {
        this.idlineaarticulo = idlineaarticulo;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Long getIdgrupolineaarticulo() {
        return idgrupolineaarticulo;
    }

    public void setIdgrupolineaarticulo(Long idgrupolineaarticulo) {
        this.idgrupolineaarticulo = idgrupolineaarticulo;
    }

    public Boolean getIndicadorPermiteDescuento() {
        return indicadorPermiteDescuento;
    }

    public void setIndicadorPermiteDescuento(Boolean indicadorPermiteDescuento) {
        this.indicadorPermiteDescuento = indicadorPermiteDescuento;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        // TODO Auto-generated method stub
        return "LineaArticulo #" + getIdlineaarticulo() + " " + getDescripcion();
    }
    // KEEP METHODS END

}
