package empresa.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import empresa.dao.LineaArticulo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LINEA_ARTICULO".
*/
public class LineaArticuloDao extends AbstractDao<LineaArticulo, Long> {

    public static final String TABLENAME = "LINEA_ARTICULO";

    /**
     * Properties of entity LineaArticulo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Idlineaarticulo = new Property(0, Long.class, "idlineaarticulo", true, "IDLINEAARTICULO");
        public final static Property Descripcion = new Property(1, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Idgrupolineaarticulo = new Property(2, Long.class, "idgrupolineaarticulo", false, "IDGRUPOLINEAARTICULO");
        public final static Property IndicadorPermiteDescuento = new Property(3, Boolean.class, "indicadorPermiteDescuento", false, "INDICADOR_PERMITE_DESCUENTO");
    };


    public LineaArticuloDao(DaoConfig config) {
        super(config);
    }

    public LineaArticuloDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LINEA_ARTICULO' (" + //
                "'IDLINEAARTICULO' INTEGER PRIMARY KEY ," + // 0: idlineaarticulo
                "'DESCRIPCION' TEXT NOT NULL ," + // 1: descripcion
                "'IDGRUPOLINEAARTICULO' INTEGER," + // 2: idgrupolineaarticulo
                "'INDICADOR_PERMITE_DESCUENTO' INTEGER);"); // 3: indicadorPermiteDescuento
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LINEA_ARTICULO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LineaArticulo entity) {
        stmt.clearBindings();

        Long idlineaarticulo = entity.getIdlineaarticulo();
        if (idlineaarticulo != null) {
            stmt.bindLong(1, idlineaarticulo);
        }
        stmt.bindString(2, entity.getDescripcion());

        Long idgrupolineaarticulo = entity.getIdgrupolineaarticulo();
        if (idgrupolineaarticulo != null) {
            stmt.bindLong(3, idgrupolineaarticulo);
        }

        Boolean indicadorPermiteDescuento = entity.getIndicadorPermiteDescuento();
        if (indicadorPermiteDescuento != null) {
            stmt.bindLong(4, indicadorPermiteDescuento ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public LineaArticulo readEntity(Cursor cursor, int offset) {
        LineaArticulo entity = new LineaArticulo( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idlineaarticulo
                cursor.getString(offset + 1), // descripcion
                cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // idgrupolineaarticulo
                cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // indicadorPermiteDescuento
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LineaArticulo entity, int offset) {
        entity.setIdlineaarticulo(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescripcion(cursor.getString(offset + 1));
        entity.setIdgrupolineaarticulo(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setIndicadorPermiteDescuento(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(LineaArticulo entity, long rowId) {
        entity.setIdlineaarticulo(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(LineaArticulo entity) {
        if(entity != null) {
            return entity.getIdlineaarticulo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
