package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOCALIDAD".
 */
public class Localidad implements java.io.Serializable {

    private Long idlocalidad;
    /** Not-null value. */
    private String descripcion;
    private Long codregion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Localidad() {
    }

    public Localidad(Long idlocalidad) {
        this.idlocalidad = idlocalidad;
    }

    public Localidad(Long idlocalidad, String descripcion, Long codregion) {
        this.idlocalidad = idlocalidad;
        this.descripcion = descripcion;
        this.codregion = codregion;
    }

    public Long getIdlocalidad() {
        return idlocalidad;
    }

    public void setIdlocalidad(Long idlocalidad) {
        this.idlocalidad = idlocalidad;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Long getCodregion() {
        return codregion;
    }

    public void setCodregion(Long codregion) {
        this.codregion = codregion;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        // TODO Auto-generated method stub
        return getDescripcion();
    }
    // KEEP METHODS END

}
