package empresa.dao;

/**
 * Created by Rescate on 31/07/2017.
 */


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LOCALIDAD_VENTACAB.
 */
public class LocalidadVentacab {

    private Long idventacab;
    private double latitud;
    private double longitud;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LocalidadVentacab() {
    }

    public LocalidadVentacab(Long idventacab) {
        this.idventacab = idventacab;
    }

    public LocalidadVentacab(Long idventacab, double latitud, double longitud) {
        this.idventacab = idventacab;
        this.latitud = latitud;
        this.longitud = longitud;
    }

    public Long getIdventacab() {
        return idventacab;
    }

    public void setIdventacab(Long idventacab) {
        this.idventacab = idventacab;
    }

    public double getLatitud() {
        return latitud;
    }

    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }

    public double getLongitud() {
        return longitud;
    }

    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return getClass().getSimpleName() + ": lat=" + latitud + " long=" + longitud;
    }


    // KEEP METHODS END

}

