package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "META_VENDEDOR".
 */
public class MetaVendedor implements java.io.Serializable {

    private Long idmetavendedor;
    private long idvendedor;
    private long idcoleccion;
    private long idproducto;
    private Long mix;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MetaVendedor() {
    }

    public MetaVendedor(Long idmetavendedor) {
        this.idmetavendedor = idmetavendedor;
    }

    public MetaVendedor(Long idmetavendedor, long idvendedor, long idcoleccion, long idproducto, Long mix) {
        this.idmetavendedor = idmetavendedor;
        this.idvendedor = idvendedor;
        this.idcoleccion = idcoleccion;
        this.idproducto = idproducto;
        this.mix = mix;
    }

    public Long getIdmetavendedor() {
        return idmetavendedor;
    }

    public void setIdmetavendedor(Long idmetavendedor) {
        this.idmetavendedor = idmetavendedor;
    }

    public long getIdvendedor() {
        return idvendedor;
    }

    public void setIdvendedor(long idvendedor) {
        this.idvendedor = idvendedor;
    }

    public long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    public long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(long idproducto) {
        this.idproducto = idproducto;
    }

    public Long getMix() {
        return mix;
    }

    public void setMix(Long mix) {
        this.mix = mix;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
