package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "METAVENDEDORCLIENTE".
 */
public class metavendedorcliente implements java.io.Serializable {

    private Long idmetavendedorcliente;
    private Long idproducto;
    private Long idcoleccion;
    private Long idlineaarticulo;
    private String idgrupolineaarticulo;
    private String idusuario;
    private Long idcliente;
    private String metacantidad;
    private Long metaventa;
    /** Not-null value. */
    private String fechainicio;
    /** Not-null value. */
    private String fechafin;
    private Boolean estado;
    private String usuariolog;
    private String fechalog;
    private Long idempresa;
    private Long idmix;
    private Long mixanterior;
    private Long comisionanterior;
    private Long ventaanterior;
    private Long cantidadanterior;
    private Long metapreciopromedio;
    private Long preciopromedioanterior;
    private Long metamix;
    private Long metacomision;
    private Long preciopromedioprenda;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public metavendedorcliente() {
    }

    public metavendedorcliente(Long idmetavendedorcliente) {
        this.idmetavendedorcliente = idmetavendedorcliente;
    }

    public metavendedorcliente(Long idmetavendedorcliente, Long idproducto, Long idcoleccion, Long idlineaarticulo, String idgrupolineaarticulo, String idusuario, Long idcliente, String metacantidad, Long metaventa, String fechainicio, String fechafin, Boolean estado, String usuariolog, String fechalog, Long idempresa, Long idmix, Long mixanterior, Long comisionanterior, Long ventaanterior, Long cantidadanterior, Long metapreciopromedio, Long preciopromedioanterior, Long metamix, Long metacomision, Long preciopromedioprenda) {
        this.idmetavendedorcliente = idmetavendedorcliente;
        this.idproducto = idproducto;
        this.idcoleccion = idcoleccion;
        this.idlineaarticulo = idlineaarticulo;
        this.idgrupolineaarticulo = idgrupolineaarticulo;
        this.idusuario = idusuario;
        this.idcliente = idcliente;
        this.metacantidad = metacantidad;
        this.metaventa = metaventa;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
        this.estado = estado;
        this.usuariolog = usuariolog;
        this.fechalog = fechalog;
        this.idempresa = idempresa;
        this.idmix = idmix;
        this.mixanterior = mixanterior;
        this.comisionanterior = comisionanterior;
        this.ventaanterior = ventaanterior;
        this.cantidadanterior = cantidadanterior;
        this.metapreciopromedio = metapreciopromedio;
        this.preciopromedioanterior = preciopromedioanterior;
        this.metamix = metamix;
        this.metacomision = metacomision;
        this.preciopromedioprenda = preciopromedioprenda;
    }

    public Long getIdmetavendedorcliente() {
        return idmetavendedorcliente;
    }

    public void setIdmetavendedorcliente(Long idmetavendedorcliente) {
        this.idmetavendedorcliente = idmetavendedorcliente;
    }

    public Long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(Long idproducto) {
        this.idproducto = idproducto;
    }

    public Long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(Long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    public Long getIdlineaarticulo() {
        return idlineaarticulo;
    }

    public void setIdlineaarticulo(Long idlineaarticulo) {
        this.idlineaarticulo = idlineaarticulo;
    }

    public String getIdgrupolineaarticulo() {
        return idgrupolineaarticulo;
    }

    public void setIdgrupolineaarticulo(String idgrupolineaarticulo) {
        this.idgrupolineaarticulo = idgrupolineaarticulo;
    }

    public String getIdusuario() {
        return idusuario;
    }

    public void setIdusuario(String idusuario) {
        this.idusuario = idusuario;
    }

    public Long getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(Long idcliente) {
        this.idcliente = idcliente;
    }

    public String getMetacantidad() {
        return metacantidad;
    }

    public void setMetacantidad(String metacantidad) {
        this.metacantidad = metacantidad;
    }

    public Long getMetaventa() {
        return metaventa;
    }

    public void setMetaventa(Long metaventa) {
        this.metaventa = metaventa;
    }

    /** Not-null value. */
    public String getFechainicio() {
        return fechainicio;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechainicio(String fechainicio) {
        this.fechainicio = fechainicio;
    }

    /** Not-null value. */
    public String getFechafin() {
        return fechafin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechafin(String fechafin) {
        this.fechafin = fechafin;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public String getUsuariolog() {
        return usuariolog;
    }

    public void setUsuariolog(String usuariolog) {
        this.usuariolog = usuariolog;
    }

    public String getFechalog() {
        return fechalog;
    }

    public void setFechalog(String fechalog) {
        this.fechalog = fechalog;
    }

    public Long getIdempresa() {
        return idempresa;
    }

    public void setIdempresa(Long idempresa) {
        this.idempresa = idempresa;
    }

    public Long getIdmix() {
        return idmix;
    }

    public void setIdmix(Long idmix) {
        this.idmix = idmix;
    }

    public Long getMixanterior() {
        return mixanterior;
    }

    public void setMixanterior(Long mixanterior) {
        this.mixanterior = mixanterior;
    }

    public Long getComisionanterior() {
        return comisionanterior;
    }

    public void setComisionanterior(Long comisionanterior) {
        this.comisionanterior = comisionanterior;
    }

    public Long getVentaanterior() {
        return ventaanterior;
    }

    public void setVentaanterior(Long ventaanterior) {
        this.ventaanterior = ventaanterior;
    }

    public Long getCantidadanterior() {
        return cantidadanterior;
    }

    public void setCantidadanterior(Long cantidadanterior) {
        this.cantidadanterior = cantidadanterior;
    }

    public Long getMetapreciopromedio() {
        return metapreciopromedio;
    }

    public void setMetapreciopromedio(Long metapreciopromedio) {
        this.metapreciopromedio = metapreciopromedio;
    }

    public Long getPreciopromedioanterior() {
        return preciopromedioanterior;
    }

    public void setPreciopromedioanterior(Long preciopromedioanterior) {
        this.preciopromedioanterior = preciopromedioanterior;
    }

    public Long getMetamix() {
        return metamix;
    }

    public void setMetamix(Long metamix) {
        this.metamix = metamix;
    }

    public Long getMetacomision() {
        return metacomision;
    }

    public void setMetacomision(Long metacomision) {
        this.metacomision = metacomision;
    }

    public Long getPreciopromedioprenda() {
        return preciopromedioprenda;
    }

    public void setPreciopromedioprenda(Long preciopromedioprenda) {
        this.preciopromedioprenda = preciopromedioprenda;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
