package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PRODUCTO".
 */
public class Producto implements java.io.Serializable {

    private Long idproducto;
    /** Not-null value. */
    private String descripcion;
    private Boolean estado;
    private Long idfamilia;
    private boolean controlstock;
    private boolean controlvirtual;
    private Boolean cajacerradastock;
    private Boolean usarcurvaproduct;

    // KEEP FIELDS - put your custom fields here
    public static final long ID_TILIBRA = 5;
    public static final long ID_CAJOVIL = 49;
    public static final long ID_QUIMICOS  = 45;
    // KEEP FIELDS END

    public Producto() {
    }

    public Producto(Long idproducto) {
        this.idproducto = idproducto;
    }

    public Producto(Long idproducto, String descripcion, Boolean estado, Long idfamilia, boolean controlstock, boolean controlvirtual, Boolean cajacerradastock, Boolean usarcurvaproduct) {
        this.idproducto = idproducto;
        this.descripcion = descripcion;
        this.estado = estado;
        this.idfamilia = idfamilia;
        this.controlstock = controlstock;
        this.controlvirtual = controlvirtual;
        this.cajacerradastock = cajacerradastock;
        this.usarcurvaproduct = usarcurvaproduct;
    }

    public Long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(Long idproducto) {
        this.idproducto = idproducto;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    public Long getIdfamilia() {
        return idfamilia;
    }

    public void setIdfamilia(Long idfamilia) {
        this.idfamilia = idfamilia;
    }

    public boolean getControlstock() {
        return controlstock;
    }

    public void setControlstock(boolean controlstock) {
        this.controlstock = controlstock;
    }

    public boolean getControlvirtual() {
        return controlvirtual;
    }

    public void setControlvirtual(boolean controlvirtual) {
        this.controlvirtual = controlvirtual;
    }

    public Boolean getCajacerradastock() {
        return cajacerradastock;
    }

    public void setCajacerradastock(Boolean cajacerradastock) {
        this.cajacerradastock = cajacerradastock;
    }

    public Boolean getUsarcurvaproduct() {
        return usarcurvaproduct;
    }

    public void setUsarcurvaproduct(Boolean usarcurvaproduct) {
        this.usarcurvaproduct = usarcurvaproduct;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {

        if(getIdproducto().longValue() == -1L) {
            return getDescripcion();
        } else {
            return getIdproducto() + " " + getDescripcion();
        }
    }

    public boolean esPrenda() {
        return getIdfamilia().longValue() == 1;
    }


    /** retorna true solo si es que ( controlstock = false Y controlvirtual = false)
     * */
    public boolean permiteNegativosVirtual() {

        return !getControlstock() && ! getControlvirtual();
    }

    @Override
    public boolean equals(Object otroProd) {
        boolean r = false;
        if(otroProd == null) r = false;

        if(otroProd instanceof Producto)
            r = ((Producto)otroProd).getIdproducto().longValue() == this.getIdproducto().longValue();
        return r;
    }

    @Override
    public int hashCode() {

        return (int)(37*getIdproducto().longValue());
    }
    // KEEP METHODS END

}
