package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import android.support.annotation.NonNull;

import tpoffline.dbentidades.Dao;

/**
 * Entity mapped to table "PROGRAMA_VISITA".
 */
public class ProgramaVisita implements java.io.Serializable, java.lang.Comparable<ProgramaVisita> {

    private Long idregistroclientelog;
    private long idoficial;
    /** Not-null value. */
    private String fechainicio;
    private String observacion;
    private long idcliente;
    private Long idtipoclientelog;
    private Long idventacab;
    private String fechaproximollamado;
    private Long idproducto;

    // KEEP FIELDS - put your custom fields here
    private boolean esPrototipoNuevo;
    private boolean estadoCambiado;
    // KEEP FIELDS END

    public ProgramaVisita() {
    }

    public ProgramaVisita(Long idregistroclientelog) {
        this.idregistroclientelog = idregistroclientelog;
    }

    public ProgramaVisita(Long idregistroclientelog, long idoficial, String fechainicio, String observacion, long idcliente, Long idtipoclientelog, Long idventacab, String fechaproximollamado, Long idproducto) {
        this.idregistroclientelog = idregistroclientelog;
        this.idoficial = idoficial;
        this.fechainicio = fechainicio;
        this.observacion = observacion;
        this.idcliente = idcliente;
        this.idtipoclientelog = idtipoclientelog;
        this.idventacab = idventacab;
        this.fechaproximollamado = fechaproximollamado;
        this.idproducto = idproducto;
    }

    public Long getIdregistroclientelog() {
        return idregistroclientelog;
    }

    public void setIdregistroclientelog(Long idregistroclientelog) {
        this.idregistroclientelog = idregistroclientelog;
    }

    public long getIdoficial() {
        return idoficial;
    }

    public void setIdoficial(long idoficial) {
        this.idoficial = idoficial;
    }

    /** Not-null value. */
    public String getFechainicio() {
        return fechainicio;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechainicio(String fechainicio) {
        this.fechainicio = fechainicio;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public long getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(long idcliente) {
        this.idcliente = idcliente;
    }

    public Long getIdtipoclientelog() {
        return idtipoclientelog;
    }

    public void setIdtipoclientelog(Long idtipoclientelog) {
        this.idtipoclientelog = idtipoclientelog;
    }

    public Long getIdventacab() {
        return idventacab;
    }

    public void setIdventacab(Long idventacab) {
        this.idventacab = idventacab;
    }

    public String getFechaproximollamado() {
        return fechaproximollamado;
    }

    public void setFechaproximollamado(String fechaproximollamado) {
        this.fechaproximollamado = fechaproximollamado;
    }

    public Long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(Long idproducto) {
        this.idproducto = idproducto;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        // TODO Auto-generated method stub
        return "Programa Visita: inicio " + getFechainicio()  + " cliente: " + getIdcliente() + " idventacab " + getIdventacab()
                + " idtipoclientelog " + getIdtipoclientelog();
    }

    public boolean esPrototipoNuevo() {
        return this.esPrototipoNuevo ;
    }

    public void  setEsPrototipoNuevo(boolean esPrototipoNuevo) {
        this.esPrototipoNuevo  = esPrototipoNuevo;
    }

    public void setEstadoCambiado(boolean estadoCambiado) {
        this.estadoCambiado = estadoCambiado;
    }

    public boolean getEstadoCambiado () {
        return estadoCambiado;
    }


    @Override
    //Original
    public int compareTo(ProgramaVisita otro) {
        return Dao.getRoDaoSession().getClienteDao().load(getIdcliente())
                .toString().compareTo(Dao.getRoDaoSession().getClienteDao().load(otro.getIdcliente()).toString());
    }
    // KEEP METHODS END

}
