package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import tpoffline.utils.Strings;

/**
 * Entity mapped to table "REFERENCIA".
 */
public class Referencia implements java.io.Serializable {

    private long idcoleccion;
    private long idproducto;
    /** Not-null value. */
    private String referencia;
    /** Not-null value. */
    private String descripcion;
    private Long grupomultiplo;

    // KEEP FIELDS - put your custom fields here
    private ProductMigradoFabrica prodMigradFabrica;
    // KEEP FIELDS END

    public Referencia() {
    }

    public Referencia(long idcoleccion, long idproducto, String referencia, String descripcion, Long grupomultiplo) {
        this.idcoleccion = idcoleccion;
        this.idproducto = idproducto;
        this.referencia = referencia;
        this.descripcion = descripcion;
        this.grupomultiplo = grupomultiplo;
    }

    public long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    public long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(long idproducto) {
        this.idproducto = idproducto;
    }

    /** Not-null value. */
    public String getReferencia() {
        return referencia;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Long getGrupomultiplo() {
        return grupomultiplo;
    }

    public void setGrupomultiplo(Long grupomultiplo) {
        this.grupomultiplo = grupomultiplo;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        String lineaCalzado = "";
        String brandCalzado = "";
        String descripcionDetalladaCalzado = "";
        if(getProdMigradFabrica() != null) {
            lineaCalzado = Strings.nullTo(getProdMigradFabrica().getLinea(), "");
            brandCalzado = Strings.nullTo(getProdMigradFabrica().getBrand(), "");
            descripcionDetalladaCalzado = Strings.nullTo(getProdMigradFabrica().getDescripcionDetallada(), "");

        }

        return  getReferencia() + " - " + getDescripcion() + " "
                + ( getGrupomultiplo() == null||getGrupomultiplo()<1 ? "" : "-(Grade: "+getGrupomultiplo()+")")
                + " " +  (lineaCalzado.length()>1 ? "- Linea "+ lineaCalzado.toUpperCase() : "")
                + " " + (brandCalzado.length()>1 ? "- "+  brandCalzado.toUpperCase() : "")
                + " " + (descripcionDetalladaCalzado.length()>1 ? "- Det: " + descripcionDetalladaCalzado : "");


    }

    public void setProductMrigradoFabrica(ProductMigradoFabrica pf) {
        this.prodMigradFabrica = pf;

    }
    public ProductMigradoFabrica getProdMigradFabrica() {
        return prodMigradFabrica;
    }
    // KEEP METHODS END

}
