package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "REGION".
 */
public class Region implements java.io.Serializable {

    private long codregion;
    /** Not-null value. */
    private String descripcion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Region() {
    }

    public Region(long codregion) {
        this.codregion = codregion;
    }

    public Region(long codregion, String descripcion) {
        this.codregion = codregion;
        this.descripcion = descripcion;
    }

    public long getCodregion() {
        return codregion;
    }

    public void setCodregion(long codregion) {
        this.codregion = codregion;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        // TODO Auto-generated method stub
        return getDescripcion();
    }
    // KEEP METHODS END

}
