package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "TIPO_DOCUMENTO".
 */
public class TipoDocumento implements java.io.Serializable {

    private String codtipodocumento;
    /** Not-null value. */
    private String descripcion;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TipoDocumento() {
    }

    public TipoDocumento(String codtipodocumento) {
        this.codtipodocumento = codtipodocumento;
    }

    public TipoDocumento(String codtipodocumento, String descripcion) {
        this.codtipodocumento = codtipodocumento;
        this.descripcion = descripcion;
    }

    public String getCodtipodocumento() {
        return codtipodocumento;
    }

    public void setCodtipodocumento(String codtipodocumento) {
        this.codtipodocumento = codtipodocumento;
    }

    /** Not-null value. */
    public String getDescripcion() {
        return descripcion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return getCodtipodocumento() + " - " + getDescripcion();
    }
    // KEEP METHODS END

}
