package empresa.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import empresa.dao.TipoPersona;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIPO_PERSONA".
*/
public class TipoPersonaDao extends AbstractDao<TipoPersona, Long> {

    public static final String TABLENAME = "TIPO_PERSONA";

    /**
     * Properties of entity TipoPersona.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Codtipopersona = new Property(0, Long.class, "codtipopersona", true, "CODTIPOPERSONA");
        public final static Property Descripcion = new Property(1, String.class, "descripcion", false, "DESCRIPCION");
    };


    public TipoPersonaDao(DaoConfig config) {
        super(config);
    }

    public TipoPersonaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TIPO_PERSONA' (" + //
                "'CODTIPOPERSONA' INTEGER PRIMARY KEY ," + // 0: codtipopersona
                "'DESCRIPCION' TEXT NOT NULL );"); // 1: descripcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TIPO_PERSONA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TipoPersona entity) {
        stmt.clearBindings();

        Long codtipopersona = entity.getCodtipopersona();
        if (codtipopersona != null) {
            stmt.bindLong(1, codtipopersona);
        }
        stmt.bindString(2, entity.getDescripcion());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public TipoPersona readEntity(Cursor cursor, int offset) {
        TipoPersona entity = new TipoPersona( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // codtipopersona
                cursor.getString(offset + 1) // descripcion
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TipoPersona entity, int offset) {
        entity.setCodtipopersona(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescripcion(cursor.getString(offset + 1));
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TipoPersona entity, long rowId) {
        entity.setCodtipopersona(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(TipoPersona entity) {
        if(entity != null) {
            return entity.getCodtipopersona();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
