package empresa.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import empresa.dao.TipoClienteLog;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIPO_CLIENTE_LOG".
*/
public class TipoClienteLogDao extends AbstractDao<TipoClienteLog, Long> {

    public static final String TABLENAME = "TIPO_CLIENTE_LOG";

    /**
     * Properties of entity TipoClienteLog.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Idtipoclientelog = new Property(0, Long.class, "idtipoclientelog", true, "IDTIPOCLIENTELOG");
        public final static Property Descripcion = new Property(1, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Tipolog = new Property(2, String.class, "tipolog", false, "TIPOLOG");
        public final static Property Reprogramar = new Property(3, Boolean.class, "reprogramar", false, "REPROGRAMAR");
    };


    public TipoClienteLogDao(DaoConfig config) {
        super(config);
    }

    public TipoClienteLogDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TIPO_CLIENTE_LOG' (" + //
                "'IDTIPOCLIENTELOG' INTEGER PRIMARY KEY ," + // 0: idtipoclientelog
                "'DESCRIPCION' TEXT NOT NULL ," + // 1: descripcion
                "'TIPOLOG' TEXT NOT NULL ," + // 2: tipolog
                "'REPROGRAMAR' INTEGER);"); // 3: reprogramar
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TIPO_CLIENTE_LOG'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TipoClienteLog entity) {
        stmt.clearBindings();

        Long idtipoclientelog = entity.getIdtipoclientelog();
        if (idtipoclientelog != null) {
            stmt.bindLong(1, idtipoclientelog);
        }
        stmt.bindString(2, entity.getDescripcion());
        stmt.bindString(3, entity.getTipolog());

        Boolean reprogramar = entity.getReprogramar();
        if (reprogramar != null) {
            stmt.bindLong(4, reprogramar ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public TipoClienteLog readEntity(Cursor cursor, int offset) {
        TipoClienteLog entity = new TipoClienteLog( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idtipoclientelog
                cursor.getString(offset + 1), // descripcion
                cursor.getString(offset + 2), // tipolog
                cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // reprogramar
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TipoClienteLog entity, int offset) {
        entity.setIdtipoclientelog(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescripcion(cursor.getString(offset + 1));
        entity.setTipolog(cursor.getString(offset + 2));
        entity.setReprogramar(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TipoClienteLog entity, long rowId) {
        entity.setIdtipoclientelog(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(TipoClienteLog entity) {
        if(entity != null) {
            return entity.getIdtipoclientelog();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
