package empresa.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import empresa.dao.TipoDocumento;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIPO_DOCUMENTO".
*/
public class TipoDocumentoDao extends AbstractDao<TipoDocumento, String> {

    public static final String TABLENAME = "TIPO_DOCUMENTO";

    /**
     * Properties of entity TipoDocumento.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Codtipodocumento = new Property(0, String.class, "codtipodocumento", true, "CODTIPODOCUMENTO");
        public final static Property Descripcion = new Property(1, String.class, "descripcion", false, "DESCRIPCION");
    };


    public TipoDocumentoDao(DaoConfig config) {
        super(config);
    }

    public TipoDocumentoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TIPO_DOCUMENTO' (" + //
                "'CODTIPODOCUMENTO' TEXT PRIMARY KEY NOT NULL ," + // 0: codtipodocumento
                "'DESCRIPCION' TEXT NOT NULL );"); // 1: descripcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TIPO_DOCUMENTO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TipoDocumento entity) {
        stmt.clearBindings();

        String codtipodocumento = entity.getCodtipodocumento();
        if (codtipodocumento != null) {
            stmt.bindString(1, codtipodocumento);
        }
        stmt.bindString(2, entity.getDescripcion());
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public TipoDocumento readEntity(Cursor cursor, int offset) {
        TipoDocumento entity = new TipoDocumento( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // codtipodocumento
                cursor.getString(offset + 1) // descripcion
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TipoDocumento entity, int offset) {
        entity.setCodtipodocumento(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setDescripcion(cursor.getString(offset + 1));
    }

    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(TipoDocumento entity, long rowId) {
        return entity.getCodtipodocumento();
    }

    /** @inheritdoc */
    @Override
    public String getKey(TipoDocumento entity) {
        if(entity != null) {
            return entity.getCodtipodocumento();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
