package empresa.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import empresa.dao.TipoCliente;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIPO_CLIENTE".
*/
public class TipoClienteDao extends AbstractDao<TipoCliente, Long> {

    public static final String TABLENAME = "TIPO_CLIENTE";

    /**
     * Properties of entity TipoCliente.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Idtipocliente = new Property(0, Long.class, "idtipocliente", true, "IDTIPOCLIENTE");
        public final static Property Descripcion = new Property(1, String.class, "descripcion", false, "DESCRIPCION");
    };


    public TipoClienteDao(DaoConfig config) {
        super(config);
    }

    public TipoClienteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TIPO_CLIENTE' (" + //
                "'IDTIPOCLIENTE' INTEGER PRIMARY KEY ," + // 0: idtipocliente
                "'DESCRIPCION' TEXT NOT NULL );"); // 1: descripcion
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TIPO_CLIENTE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TipoCliente entity) {
        stmt.clearBindings();

        Long idtipocliente = entity.getIdtipocliente();
        if (idtipocliente != null) {
            stmt.bindLong(1, idtipocliente);
        }
        stmt.bindString(2, entity.getDescripcion());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public TipoCliente readEntity(Cursor cursor, int offset) {
        TipoCliente entity = new TipoCliente( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // idtipocliente
                cursor.getString(offset + 1) // descripcion
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TipoCliente entity, int offset) {
        entity.setIdtipocliente(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescripcion(cursor.getString(offset + 1));
    }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TipoCliente entity, long rowId) {
        entity.setIdtipocliente(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(TipoCliente entity) {
        if(entity != null) {
            return entity.getIdtipocliente();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
