package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ULTIMA_VENTA".
 */
public class UltimaVenta {

    private Long idultimaventa;
    private long idcliente;
    private long idproducto;
    /** Not-null value. */
    private String referencia;
    private Long cantidadtotal;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UltimaVenta() {
    }

    public UltimaVenta(Long idultimaventa) {
        this.idultimaventa = idultimaventa;
    }

    public UltimaVenta(Long idultimaventa, long idcliente, long idproducto, String referencia, Long cantidadtotal) {
        this.idultimaventa = idultimaventa;
        this.idcliente = idcliente;
        this.idproducto = idproducto;
        this.referencia = referencia;
        this.cantidadtotal = cantidadtotal;
    }

    public Long getIdultimaventa() {
        return idultimaventa;
    }

    public void setIdultimaventa(Long idultimaventa) {
        this.idultimaventa = idultimaventa;
    }

    public long getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(long idcliente) {
        this.idcliente = idcliente;
    }

    public long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(long idproducto) {
        this.idproducto = idproducto;
    }

    /** Not-null value. */
    public String getReferencia() {
        return referencia;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    public Long getCantidadtotal() {
        return cantidadtotal;
    }

    public void setCantidadtotal(Long cantidadtotal) {
        this.cantidadtotal = cantidadtotal;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
