package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import tpoffline.Config;

/**
 * Entity mapped to table "USUARIO".
 */
public class Usuario {

    private Long idusuario;
    private long idpersona;
    /** Not-null value. */
    private String nombres;
    /** Not-null value. */
    private String apellidos;
    /** Not-null value. */
    private String usuario;
    /** Not-null value. */
    private String clave;
    /** Not-null value. */
    private String nrodocumento;
    private Boolean estado;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Usuario() {
    }

    public Usuario(Long idusuario) {
        this.idusuario = idusuario;
    }

    public Usuario(Long idusuario, long idpersona, String nombres, String apellidos, String usuario, String clave, String nrodocumento, Boolean estado) {
        this.idusuario = idusuario;
        this.idpersona = idpersona;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.usuario = usuario;
        this.clave = clave;
        this.nrodocumento = nrodocumento;
        this.estado = estado;
    }

    public Long getIdusuario() {
        return idusuario;
    }

    public void setIdusuario(Long idusuario) {
        this.idusuario = idusuario;
    }

    public long getIdpersona() {
        return idpersona;
    }

    public void setIdpersona(long idpersona) {
        this.idpersona = idpersona;
    }

    /** Not-null value. */
    public String getNombres() {
        return nombres;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    /** Not-null value. */
    public String getApellidos() {
        return apellidos;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    /** Not-null value. */
    public String getUsuario() {
        return usuario;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    /** Not-null value. */
    public String getClave() {
        return clave;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setClave(String clave) {
        this.clave = clave;
    }

    /** Not-null value. */
    public String getNrodocumento() {
        return nrodocumento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNrodocumento(String nrodocumento) {
        this.nrodocumento = nrodocumento;
    }

    public Boolean getEstado() {
        return estado;
    }

    public void setEstado(Boolean estado) {
        this.estado = estado;
    }

    // KEEP METHODS - put your custom methods here

    public String getUsuarioLogString() {
        return Config.USUARIO_LOG_PREFIX + getUsuario();
    }

    @Override
    public String toString() {

        return getIdusuario() +  " " + getNombres() + " " + getApellidos();
    }
    // KEEP METHODS END

}
