package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "VENTA_CAB".
 */
public class VentaCab implements java.io.Serializable {

    private Long idventacab;
    /** Not-null value. */
    private java.util.Date fechaoperacion;
    /** Not-null value. */
    private java.util.Date fecha;
    private Long idusuario;
    private Long idoficial;
    private Long idcliente;
    private String codmoneda;
    private long idformapago;
    private double importe;
    private Double importeequivalente;
    private Long codsucursal;
    /** Not-null value. */
    private java.util.Date fechapactoentrega;
    private long cantidadtotal;
    private long idproducto;
    private Long promediodescuento;
    private long idcoleccion;
    /** Not-null value. */
    private String tipo;
    private String observacion;
    private String condicion;
    private Double tasapromocion;
    private Long quincenaentrega;
    private Long quincenaentregames;
    private boolean enviado;
    private Long getIdventacab;
    private String datosproduccionstring;
    private Boolean entregainmediata;
    private Long idpromocion;
    private Long idescala;
    private Double comision;
    private long idempresa;
    private boolean esTipoCalzado;
    private boolean esFlete;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public VentaCab() {
    }

    public VentaCab(Long idventacab) {
        this.idventacab = idventacab;
    }

    public VentaCab(Long idventacab, java.util.Date fechaoperacion, java.util.Date fecha, Long idusuario, Long idoficial, Long idcliente, String codmoneda, long idformapago, double importe, Double importeequivalente, Long codsucursal, java.util.Date fechapactoentrega, long cantidadtotal, long idproducto, Long promediodescuento, long idcoleccion, String tipo, String observacion, String condicion, Double tasapromocion, Long quincenaentrega, Long quincenaentregames, boolean enviado, Long getIdventacab, String datosproduccionstring, Boolean entregainmediata, Long idpromocion, Long idescala, Double comision, long idempresa, boolean esTipoCalzado, boolean esFlete) {
        this.idventacab = idventacab;
        this.fechaoperacion = fechaoperacion;
        this.fecha = fecha;
        this.idusuario = idusuario;
        this.idoficial = idoficial;
        this.idcliente = idcliente;
        this.codmoneda = codmoneda;
        this.idformapago = idformapago;
        this.importe = importe;
        this.importeequivalente = importeequivalente;
        this.codsucursal = codsucursal;
        this.fechapactoentrega = fechapactoentrega;
        this.cantidadtotal = cantidadtotal;
        this.idproducto = idproducto;
        this.promediodescuento = promediodescuento;
        this.idcoleccion = idcoleccion;
        this.tipo = tipo;
        this.observacion = observacion;
        this.condicion = condicion;
        this.tasapromocion = tasapromocion;
        this.quincenaentrega = quincenaentrega;
        this.quincenaentregames = quincenaentregames;
        this.enviado = enviado;
        this.getIdventacab = getIdventacab;
        this.datosproduccionstring = datosproduccionstring;
        this.entregainmediata = entregainmediata;
        this.idpromocion = idpromocion;
        this.idescala = idescala;
        this.comision = comision;
        this.idempresa = idempresa;
        this.esTipoCalzado = esTipoCalzado;
        this.esFlete = esFlete;
    }

    public Long getIdventacab() {
        return idventacab;
    }

    public void setIdventacab(Long idventacab) {
        this.idventacab = idventacab;
    }

    /** Not-null value. */
    public java.util.Date getFechaoperacion() {
        return fechaoperacion;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechaoperacion(java.util.Date fechaoperacion) {
        this.fechaoperacion = fechaoperacion;
    }

    /** Not-null value. */
    public java.util.Date getFecha() {
        return fecha;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    public Long getIdusuario() {
        return idusuario;
    }

    public void setIdusuario(Long idusuario) {
        this.idusuario = idusuario;
    }

    public Long getIdoficial() {
        return idoficial;
    }

    public void setIdoficial(Long idoficial) {
        this.idoficial = idoficial;
    }

    public Long getIdcliente() {
        return idcliente;
    }

    public void setIdcliente(Long idcliente) {
        this.idcliente = idcliente;
    }

    public String getCodmoneda() {
        return codmoneda;
    }

    public void setCodmoneda(String codmoneda) {
        this.codmoneda = codmoneda;
    }

    public long getIdformapago() {
        return idformapago;
    }

    public void setIdformapago(long idformapago) {
        this.idformapago = idformapago;
    }

    public double getImporte() {
        return importe;
    }

    public void setImporte(double importe) {
        this.importe = importe;
    }

    public Double getImporteequivalente() {
        return importeequivalente;
    }

    public void setImporteequivalente(Double importeequivalente) {
        this.importeequivalente = importeequivalente;
    }

    public Long getCodsucursal() {
        return codsucursal;
    }

    public void setCodsucursal(Long codsucursal) {
        this.codsucursal = codsucursal;
    }

    /** Not-null value. */
    public java.util.Date getFechapactoentrega() {
        return fechapactoentrega;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFechapactoentrega(java.util.Date fechapactoentrega) {
        this.fechapactoentrega = fechapactoentrega;
    }

    public long getCantidadtotal() {
        return cantidadtotal;
    }

    public void setCantidadtotal(long cantidadtotal) {
        this.cantidadtotal = cantidadtotal;
    }

    public long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(long idproducto) {
        this.idproducto = idproducto;
    }

    public Long getPromediodescuento() {
        return promediodescuento;
    }

    public void setPromediodescuento(Long promediodescuento) {
        this.promediodescuento = promediodescuento;
    }

    public long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    /** Not-null value. */
    public String getTipo() {
        return tipo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getObservacion() {
        return observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public String getCondicion() {
        return condicion;
    }

    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }

    public Double getTasapromocion() {
        return tasapromocion;
    }

    public void setTasapromocion(Double tasapromocion) {
        this.tasapromocion = tasapromocion;
    }

    public Long getQuincenaentrega() {
        return quincenaentrega;
    }

    public void setQuincenaentrega(Long quincenaentrega) {
        this.quincenaentrega = quincenaentrega;
    }

    public Long getQuincenaentregames() {
        return quincenaentregames;
    }

    public void setQuincenaentregames(Long quincenaentregames) {
        this.quincenaentregames = quincenaentregames;
    }

    public boolean getEnviado() {
        return enviado;
    }

    public void setEnviado(boolean enviado) {
        this.enviado = enviado;
    }




    public String getDatosproduccionstring() {
        return datosproduccionstring;
    }

    public void setDatosproduccionstring(String datosproduccionstring) {
        this.datosproduccionstring = datosproduccionstring;
    }

    public Boolean getEntregainmediata() {
        return entregainmediata;
    }

    public void setEntregainmediata(Boolean entregainmediata) {
        this.entregainmediata = entregainmediata;
    }

    public Long getIdpromocion() {
        return idpromocion;
    }

    public void setIdpromocion(Long idpromocion) {
        this.idpromocion = idpromocion;
    }

    public Long getIdescala() {
        return idescala;
    }

    public void setIdescala(Long idescala) {
        this.idescala = idescala;
    }

    public Double getComision() {
        return comision;
    }

    public void setComision(Double comision) {
        this.comision = comision;
    }

    public long getIdempresa() {
        return idempresa;
    }

    public void setIdempresa(long idempresa) {
        this.idempresa = idempresa;
    }

    public boolean getEsTipoCalzado() {
        return esTipoCalzado;
    }

    public void setEsTipoCalzado(boolean esTipoCalzado) {
        this.esTipoCalzado = esTipoCalzado;
    }

    public boolean getEsFlete() {
        return esFlete;
    }

    public void setEsFlete(boolean esFlete) {
        this.esFlete = esFlete;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {

        return "VentaCab #Id: " + getIdventacab() + " Importe :" + getImporte() + " cantidad: " + getCantidadtotal()
                + " descuento promedio:  " + getPromediodescuento();
    }
    // KEEP METHODS END

}
