package empresa.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "VENTA_DET".
 */
public class VentaDet {

    private Long idventadet;
    private long idventacab;
    private long idarticulo;
    private Long cantidad;
    private Long idproducto;
    private Long idcoleccion;
    private Long porcentajedescuento;
    private Boolean tienedescuentopropio;
    private Double precioventa;
    private Double preciocosto;
    private Double precio;
    private Double preciocostoeq;
    private Double preciocostorealeq;
    private Double impuesto;
    private Double total;
    private Double tasapromocion;
    private Long cantidadstockfisico;
    private Long cantidadstockvirtual;
    private Long idproductMirgradocalzado;
    private String talleCalzado;
    private String colorCalzado;
    private Long idarticulosucursalubicacion;

    // KEEP FIELDS - put your custom fields here

    private Articulo articuloDet;
    // KEEP FIELDS END

    public VentaDet() {
    }

    public VentaDet(Long idventadet) {
        this.idventadet = idventadet;
    }

    public VentaDet(Long idventadet, long idventacab, long idarticulo, Long cantidad, Long idproducto, Long idcoleccion, Long porcentajedescuento, Boolean tienedescuentopropio, Double precioventa, Double preciocosto, Double precio, Double preciocostoeq, Double preciocostorealeq, Double impuesto, Double total, Double tasapromocion, Long cantidadstockfisico, Long cantidadstockvirtual, Long idproductMirgradocalzado, String talleCalzado, String colorCalzado, Long idarticulosucursalubicacion) {
        this.idventadet = idventadet;
        this.idventacab = idventacab;
        this.idarticulo = idarticulo;
        this.cantidad = cantidad;
        this.idproducto = idproducto;
        this.idcoleccion = idcoleccion;
        this.porcentajedescuento = porcentajedescuento;
        this.tienedescuentopropio = tienedescuentopropio;
        this.precioventa = precioventa;
        this.preciocosto = preciocosto;
        this.precio = precio;
        this.preciocostoeq = preciocostoeq;
        this.preciocostorealeq = preciocostorealeq;
        this.impuesto = impuesto;
        this.total = total;
        this.tasapromocion = tasapromocion;
        this.cantidadstockfisico = cantidadstockfisico;
        this.cantidadstockvirtual = cantidadstockvirtual;
        this.idproductMirgradocalzado = idproductMirgradocalzado;
        this.talleCalzado = talleCalzado;
        this.colorCalzado = colorCalzado;
        this.idarticulosucursalubicacion = idarticulosucursalubicacion;
    }

    public Long getIdventadet() {
        return idventadet;
    }

    public void setIdventadet(Long idventadet) {
        this.idventadet = idventadet;
    }

    public long getIdventacab() {
        return idventacab;
    }

    public void setIdventacab(long idventacab) {
        this.idventacab = idventacab;
    }

    public long getIdarticulo() {
        return idarticulo;
    }

    public void setIdarticulo(long idarticulo) {
        this.idarticulo = idarticulo;
    }

    public Long getCantidad() {
        return cantidad;
    }

    public void setCantidad(Long cantidad) {
        this.cantidad = cantidad;
    }

    public Long getIdproducto() {
        return idproducto;
    }

    public void setIdproducto(Long idproducto) {
        this.idproducto = idproducto;
    }

    public Long getIdcoleccion() {
        return idcoleccion;
    }

    public void setIdcoleccion(Long idcoleccion) {
        this.idcoleccion = idcoleccion;
    }

    public Long getPorcentajedescuento() {
        return porcentajedescuento;
    }

    public void setPorcentajedescuento(Long porcentajedescuento) {
        this.porcentajedescuento = porcentajedescuento;
    }

    public Boolean getTienedescuentopropio() {
        return tienedescuentopropio;
    }

    public void setTienedescuentopropio(Boolean tienedescuentopropio) {
        this.tienedescuentopropio = tienedescuentopropio;
    }

    public Double getPrecioventa() {
        return precioventa;
    }

    public void setPrecioventa(Double precioventa) {
        this.precioventa = precioventa;
    }

    public Double getPreciocosto() {
        return preciocosto;
    }

    public void setPreciocosto(Double preciocosto) {
        this.preciocosto = preciocosto;
    }

    public Double getPrecio() {
        return precio;
    }

    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    public Double getPreciocostoeq() {
        return preciocostoeq;
    }

    public void setPreciocostoeq(Double preciocostoeq) {
        this.preciocostoeq = preciocostoeq;
    }

    public Double getPreciocostorealeq() {
        return preciocostorealeq;
    }

    public void setPreciocostorealeq(Double preciocostorealeq) {
        this.preciocostorealeq = preciocostorealeq;
    }

    public Double getImpuesto() {
        return impuesto;
    }

    public void setImpuesto(Double impuesto) {
        this.impuesto = impuesto;
    }

    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public Double getTasapromocion() {
        return tasapromocion;
    }

    public void setTasapromocion(Double tasapromocion) {
        this.tasapromocion = tasapromocion;
    }

    public Long getCantidadstockfisico() {
        return cantidadstockfisico;
    }

    public void setCantidadstockfisico(Long cantidadstockfisico) {
        this.cantidadstockfisico = cantidadstockfisico;
    }

    public Long getCantidadstockvirtual() {
        return cantidadstockvirtual;
    }

    public void setCantidadstockvirtual(Long cantidadstockvirtual) {
        this.cantidadstockvirtual = cantidadstockvirtual;
    }

    public Long getIdproductMirgradocalzado() {
        return idproductMirgradocalzado;
    }

    public void setIdproductMirgradocalzado(Long idproductMirgradocalzado) {
        this.idproductMirgradocalzado = idproductMirgradocalzado;
    }

    public String getTalleCalzado() {
        return talleCalzado;
    }

    public void setTalleCalzado(String talleCalzado) {
        this.talleCalzado = talleCalzado;
    }

    public String getColorCalzado() {
        return colorCalzado;
    }

    public void setColorCalzado(String colorCalzado) {
        this.colorCalzado = colorCalzado;
    }

    public Long getIdarticulosucursalubicacion() {
        return idarticulosucursalubicacion;
    }

    public void setIdarticulosucursalubicacion(Long idarticulosucursalubicacion) {
        this.idarticulosucursalubicacion = idarticulosucursalubicacion;
    }

    // KEEP METHODS - put your custom methods here

    @Override
    public String toString() {
        return "VentaDet id# " + getIdventadet() + " idventacab: " + getIdventacab() + " precioventa: " + getPrecioventa()
                + " precio: " + getPrecio() + " preciocostoEq" +getPreciocostoeq();
    }

    // usado para guardar en XML
    public void setArticuloInstance(Articulo articuloDet) {
        this.articuloDet = articuloDet;
    }

    public Articulo getArticuloInstance() {
        return articuloDet;
    }
    // KEEP METHODS END

}
